### ISSUE TITLE
Not an issue, just a suggestion

### ISSUE THREAD

**Issue by shinbonlin** [jsor/lity#1]
Geart and light-weight plugin, I use it instead of FancyBox.

How to allow to open opposite path as iframe ?

For example:

&lt;a href="/post/preview/" data-lity&gt;Preview Post&lt;/a&gt;

**Comment by jsor** [comment]
Very good suggestion. I've release a new version where the iFrame handler is the last handler in the auto-detection chain and can now handle all types of URLs.

So, your example should work now.

https://github.com/jsor/lity/releases/tag/v1.2.0

**Comment by shinbonlin** [comment]
Thank you!
