### ISSUE TITLE
Auto open YouTube on page load

### ISSUE THREAD

**Issue by IGSmith** [jsor/lity#100]
Hi, have tried to follow instructions from closed post #6 to activate Lity lightbox on page load, but need help?

From your answer on #6 I replaced the <your_url_or_selector_or_html> with a YouTube link, but nothing happens when opening the page. 

If you could outline what I need to do? Thanks.

**Comment by jsor** [comment]
The solution in the issue is targetted at the 1.x API, if you use 2.x the code is simply

```js
$(function() {
    lity('https://www.youtube.com/watch?v=XSGBVzeBUbk');
});
```

**Comment by IGSmith** [comment]
Thanks for your reply. I copied/pasted this into the <head> part of my page as:
<script type="text/javascript">

But when opening page it does not auto-load the lightbox?
Maybe this is wrong what I have done?
Not sure what you meant by 1.x API / 2.x API (Sorry, I'm fairly new to this).

**Comment by ayulayol** [comment]
IG Smith. how to the auto popup plsease help me
