### ISSUE TITLE
Auto close lightbox when YouTube video ends?

### ISSUE THREAD

**Issue by IGSmith** [jsor/lity#101]
Hi, is it possible to automatically close the lightbox when the YouTube video has come to an end?

I have the lightbox auto load when landing on the page.

If this is not possible, can I set a timed close of the lightbox?

**Comment by jsor** [comment]
This can probably implemented using https://developers.google.com/youtube/iframe_api_reference but is definitly out of the scope of Lity.

**Comment by IGSmith** [comment]
OK, thanks. How about a timed close option? (i.e.; I set a time of about 15 seconds to auto close the lightbox?

**Comment by liltinkerer** [comment]
$(document).on('lity:open', function(event, instance) {
  setTimeout(
    function() {
        // close lity
    }, 5000);}); // 5000 ms = 5 sec

**Comment by jsor** [comment]
You can simply use `setTimeout()` to close the lightbox automatically.

**Comment by IGSmith** [comment]
Have got this on the page to auto open the lightbox:
`$(function() {
    lity('https://www.youtube.com/watch?v=rLHAuDsdfPI&rel=0');
});`
Tried liltinkerer's suggested script, but not working. Please advise?

**Comment by jsor** [comment]
```js
$(function() { 
    var instance = lity('https://www.youtube.com/watch?v=rLHAuDsdfPI&rel=0');

    setTimeout(function() {
        instance.close();
    }, 5000);}); // 5000 ms = 5 sec
});

**Comment by IGSmith** [comment]
Thanks, but the auto-open no longer works, and with the link I have on the page to launch the same video - it does not auto close after 5 seconds?

**Comment by jsor** [comment]
I fixed the code in my comment, could you try again?

**Comment by IGSmith** [comment]
Now works perfectly. Thank you.

**Comment by rodboc** [comment]
Is also a way to automatically close it when data-lity is used on the html?
