### ISSUE TITLE
Feature Request: youtube playlist

### ISSUE THREAD

**Issue by get-high** [jsor/lity#102]
is it possible?

**Comment by jsor** [comment]
Yes, just use the playlist URL and lity should embed the playlist correctly.

**Comment by starfrosch** [comment]
I tried this, but I only get a blank page.

https://www.youtube.com/playlist?list=PLkurxeBet7kvW838xNRceWzfCzp3aREMo

**Comment by starfrosch** [comment]
Got it, I have to use this URL

https://www.youtube.com/watch?v=agcHZUHdiv0&list=PLkurxeBet7kvW838xNRceWzfCzp3aREMo
