### ISSUE TITLE
a11y: focus lost after pressing ESC

### ISSUE THREAD

**Issue by vellip** [jsor/lity#104]
You do seem to put the focus back on the element that triggered the lightbox when the user clicks the Close button. But when the user presses ESC, the focus jumps to the `body` element.

**Comment by jsor** [comment]
I cannot reproduce this. Can you give some more informations? Lity version, Browser etc.

**Comment by vellip** [comment]
I simply checked on your demo page: http://sorgalla.com/lity/ It happened on Chrome 56.

Steps to reproduce:
1. click the Image button/link
2. wait for image load
3. press ESC

The focus is not back on the  Image button/link as it should be.

However, if you do:
1. click the Image button/link
2. wait for image load
3. click the cross

the Focus is back where it was before the lightbox opened.

**Comment by jsor** [comment]
Ah yes, the site used an older version of Lity. I've updated the site, check again ;)

**Comment by vellip** [comment]
That's better!
