### ISSUE TITLE
lity height to auto adjust to content

### ISSUE THREAD

**Issue by nickdael** [jsor/lity#105]
![adjust](https://cloud.githubusercontent.com/assets/16138667/24201481/1ca91a28-0f4b-11e7-9dfd-cee35317af98.png)

Lity was used to show a link (separate URL from the page) that contains a form. 

(1) is there a way to either set the height of the lightbox for this specific one
(2) or maybe an auto adjust of the lightbox' height to show all the fields of the form

Thanks.

**Comment by jsor** [comment]
Both is not possible, sorry :(

**Comment by caseycallis** [comment]
You can definitely resize the content by changing the CSS. I've used Lity in many projects, and I almost always modify the stylesheet to make the Lity container force an aspect ratio. That way I can just use media queries to bump up the aspect ratio once the content starts to get taller. 

Here's an example of a force aspect ratio on a list apart...
https://alistapart.com/d/creating-intrinsic-ratios-for-video/example2.html
