### ISSUE TITLE
Close button moves away on hover

### ISSUE THREAD

**Issue by andreibkn** [jsor/lity#106]
Hi,
The title describes it all: whatever lity popup has the close button moving away on mouse hover.

Regards,
Andrei

**Comment by jsor** [comment]
I'm not aware of this issue. Could you provide more information? A reproducible test case, browser (versions) were you're experiencing this issue etc.

**Comment by andreibkn** [comment]
1. Go to http://careers.emag.ro/
2. Click "terms and conditions" at the bottom of the homepage
3. A lity inline html page will open
4. Hover your pointer over the close button

**Comment by jsor** [comment]
You have a global `button:hover` style which sets some styles like

```css
height: 2.5em;
line-height: 2.5em;
```

This makes the button jump.

**Comment by andreibkn** [comment]
Danke Jan, this did the trick.
