### ISSUE TITLE
Lity + form + iphone + UX

### ISSUE THREAD

**Issue by yannbayo** [jsor/lity#107]
Hi,
Thank's for this awesome plugin !
however, the forms jump to the screen when selecting a field.
I only notice that on iphone (6s).
Do you think it can be fixed ?
Thank you so much for your response.
Chears

**Comment by jsor** [comment]
Yes, this is a "feature", i'm not sure and don't know if this can be prevented.

**Comment by davelens** [comment]
> however, the forms jump to the screen when selecting a field.

> Yes, this is a "feature", i'm not sure and don't know if this can be prevented.

This is the same behaviour as described in https://bugs.webkit.org/show_bug.cgi?id=158276. This issue should be fixed now with the recent iOS update (10.3.1).

**Comment by yannbayo** [comment]
Thank you @davelens for your feedback.
I'm going to check this point.
Regards
