### ISSUE TITLE
How is the Popup Created?

### ISSUE THREAD

**Issue by benagainwa** [jsor/lity#108]
Trying to track Vimeo videos with GA, which requires the use of a true embed tag. Developer has modified lity to load using the embed, but analytics completely ignores it.

Want to know how the window is being opened. Perhaps there needs to be a function to insert Google Tag Manager into this window function?

Thanks,
Ben Brooks

**Comment by jsor** [comment]
By default, vimeo videos are loaded via iframes. If someone has modified the lity code for you, i'm not sure i can help much here. Everything is documented in the [readme.](https://github.com/jsor/lity/tree/v2.2.2#lity).

If you could setup a test case with some actual code, i can probably help then.

**Comment by benagainwa** [comment]
Hi Jan, thanks for reaching out.

Our test page is here: http://nintexdevtest.westus.cloudapp.azure.com/company/events-webinars

Video that uses the code is under On-Demand Webinars, "The New Battle Cry in Transformation is Automation" title or "View now" button.

We’re trying to get the popup to load the video using code similar to this:

<iframe src="https://player.vimeo.com/video/183407371?api=1&player_id=vimeo-player-155" id="vimeo-player-155" width="640" height="360" frameborder="0" data-progress="true" data-seek="true" data-bounce="false" webkitallowFullScreen mozallowfullscreen allowFullScreen></iframe>

I can hook into that with GA to get full tracking.

Any thoughts you may have would be most appreciated!

Ben

**Comment by jsor** [comment]
You can overwrite the vimeo handler. Use something like this after lity is included:

```js
// Store old handler
var oldVimeoHandler = lity.handlers('vimeo');

lity.handlers('vimeo', function(target) {
    var contentHtml = oldVimeoHandler(target);

    if (!contentHtml) {
        return false;
    }

    // Transform content to jquery object
    var content = $(contentHtml);

    // get the iframe element
    var iframe = content.find('iframe');

    // Manipulate the iframe here
    iframe.attr('data-bounce', 'false');

    return content;
});
```
