### ISSUE TITLE
open YouTube Video with start time (URL args)

### ISSUE THREAD

**Issue by pfmd86** [jsor/lity#109]
Hi,
I want to use lity for a project. I want to open a YT-Video at a defined timestamp.
I want to use the t-Parameter from YouTube for this.
My link looks like this:
`https://www.youtube.com/watch?v=sMm9zi5Aebs&t=5m8s`

I'm adding the _&t=5m8s_ part with a php function. But when i click the link the video starts from the beginning.

Is it possible to use lity with the URL arguments?

**Comment by pfmd86** [comment]
I think i've found a working solution. I've customized the youtubeHandle-function.

`    function youtubeHandler(target) {
        var matches = _youtubeRegex.exec(target);

        if (!matches) {
            return false;
        }
	**var starttime = matches[5].split('=')[1];**
        return iframeHandler(
            transferHash(
                target,
                appendQueryParams(
                    'https://www.youtube' + (matches[2] || '') + '.com/embed/' + matches[4],
                    $.extend(
                        {
                            autoplay: 1,
			    **start: starttime**
                        },
                        parseQueryParams(matches[5] || '')
                    )
                )
            )
        );
    }`

**Comment by jsor** [comment]
You can use the `start` parameter in the link URL (see also #75).

**Comment by pfmd86** [comment]
Ok, so i have to deliver **?start=123s** at the end of the URL. So i can use the default lity again. I will check this. Thanks for the support and the great project!

**Comment by jsor** [comment]
Great, closing for now. Feel free to reopen if you have further questions.
