### ISSUE TITLE
Custom Close Button

### ISSUE THREAD

**Issue by jezthomp** [jsor/lity#110]
I’m trying to add a custom close button but i’m not great with JS.

I’ve a default setup with a data-lity within an a link.

I then want to close that lightbox with the following but i’m just getting an error that it cannot find an instance of Lity :(

`$(".test-button").unbind('click').click(function(){
		   Lity.close();
 });`

**Comment by jsor** [comment]
Just add a `data-lity-close` to the custom button element.

**Comment by jezthomp** [comment]
Perfect thank you.
