### ISSUE TITLE
Multiple inline content wordpress

### ISSUE THREAD

**Issue by TasGuerciMaia** [jsor/lity#113]
I'm inserting multiple inline contents with wordpress editor. But the all links are calling always the first content. Can I use lity this way or should I insert on the page template??

**Comment by jsor** [comment]
Can't say much without seeing how you aczually use it. I guess you use the same id for all inline containers. They must be different to be correctly targeted by Lity.

```html

<a href="#inline1">Inline1</a>
<div id="inline1">...</div>

<a href="#inline2">Inline2</a>
<div id="inline2">...</div>
```

**Comment by jsor** [comment]
Closing for now, feel free to reopen if needed.
