### ISSUE TITLE
NYTimes iFrame blocked

### ISSUE THREAD

**Issue by inglesuniversal** [jsor/lity#116]
Hello: I have an API key from NYTIMES and wish to load the latest news into lity's iframe option... Sadly.. I am getting this error... Refuse to Display in a frame because it set 'X-Frame-Options' to 'deny'.
`

          var myBriefing = result.results["0"].short_url;
          var lightbox = lity(myBriefing);
          // Bind as an event handler
          $(document).on('click', '[data-lightbox]', lity);

`

Is there a way for lity to open this page inside an IFRAME without having to open a new browser tab?

Thanks

**Comment by jsor** [comment]
No, unfortunately not. The only way is to proxy, eg. through a PHP script. You call that script (which is located on you your server) and that script fetches the content from NYTIMES and simply outputs the result.
