### ISSUE TITLE
kindly check this tiny LITY code...

### ISSUE THREAD

**Issue by inglesuniversal** [jsor/lity#118]
I have version 2.2.1 installed on my site and I've read your notes dozens of times, but can't figure out a way to close a simple YouTube Video lightbox triggered with the following command...

`        var lightbox = lity('https://youtube.com?v=********');
        // Bind as an event handler
        $(document).on('click', '[data-lightbox]', lity);     `

That's exactly the code and wording I use .... 

HOW to close CURRENT lightbox ... Can you kindly show me how to do it using the VAR NAMES I'm using, since that's the part where I get lost.  

Thanks.

**Comment by jsor** [comment]
First, you should use only one of the setup methods. The second line isn't needed if you just want to open a lightbox manually.

This opens a lightbox and return a [`Lity`](https://github.com/jsor/lity/tree/v2.2.1#the-lity-instance) instance which is stored in the `lightbox` variable.

```js
var lightbox = lity('https://youtube.com?v=********');
```

You can close the the lightbox with the [`close()`](https://github.com/jsor/lity/tree/v2.2.1#lityclose) method.

```js
lightbox.close();
````

The second line isn't needed in your case. It just binds a delegated event to alle elements with a `data-lightbox` attribute so you don't need to setup manually.

```js
$(document).on('click', '[data-lightbox]', lity);
```

You can now use as much elements in your document as you want and each link opens a lightbox.

```html
<a href="https://youtube.com?v=********" data-lightbox>Video 1</a>
<a href="https://youtube.com?v=********" data-lightbox>Video 2</a>
<a href="https://youtube.com?v=********" data-lightbox>Video 3</a>
```

**Comment by inglesuniversal** [comment]
ok I removed the line you suggested and when calling the   lightbox.close();    function,   I get this error inside the js console --->  lightbox.close is not a function

how can I fix this?

**Comment by jsor** [comment]
Could you setup a reproducible test case, eg. on jsfiddle?

**Comment by jsor** [comment]
Closing for now due to lack of feedback, feel free to reopen if needed.
