### ISSUE TITLE
change default width of lightbox

### ISSUE THREAD

**Issue by dk632611** [jsor/lity#119]
Is there a way to "programmatically" change the width of lightbox? I know that lightbox takes up 100% of the width of the page. But I'm not talking about that, but the width of the black box that can't be seen through, which seems to take up about 60% of the screen. 

Please see the red arrows in the attachment.
![screenhunter_285 jul 06 17 41](https://user-images.githubusercontent.com/29964796/27938382-a50de6da-6272-11e7-8ad5-8b5dcf84a247.jpg)

**Comment by jsor** [comment]
I'm not sure what you mean exactly and the screenshot doesn't make it more clear, sorry Could you provide a little bit more information? Ideally with a reproducible test case.

**Comment by dk632611** [comment]
Hi jsor

  Thanks for the reply.

  Here is exactly what I'm doing:

1) call an anchor tag with reference to a php file and your data-lity:

   <a href="user-profile-form.php?userId=new" class="btn-green" data-lity>Add New User</a>

2) The lightbox comes up correctly with a form I create in the user-profile-form.php file.

3) Even though the lightbox comes up, the width of the opaque area is much wider then 
the form I create. You can see this here (the red arrows mark the width of the area Lity
provides me, the blue arrows are the width of my form (which I myself set).

![screenhunter_289 jul 10 20 31](https://user-images.githubusercontent.com/29964796/28050016-eb87c92e-65af-11e7-8f77-5cfc3d43a2dd.jpg)

4)  I would like the Lity provided area to be the same width as my form. I have gotten it to
work perfectly (the Lity area shrinks to my form width)  with an inline reference by equating
the href to the form div id:

<a href="#userFormDivID" class="btn-green" data-lity>Add New User</a> 

 However, I need to pass parameters to the php file, so this solution does not work for me.

Thanks

**Comment by dk632611** [comment]
It seems your commenting system is turning my anchor tags above into actually links. That is why you see "Add New User" above. So #1 example above should be:
  href="user-profile-form.php?userId=new" class="btn-green" data-lity>Add New User 

and #4 example above should be:

  href="#userFormDivID" class="btn-green" data-lity>Add New User

**Comment by jsor** [comment]
The problem is, that you're loading the content vai an iframe. Iframes have a fixed width because Lity cannot know the exact width of the loaded content.

**Comment by dk632611** [comment]
Hi Jsor

   Thanks for the reply. But there are absolute no iframes involved. Here is the
exact code, but the only difference is that in the first the href is calling the div ID directly in the
file "user-profile-form.php" (which resizes correctly) and the other the href is calling the "user-profile-form.php" directly (which does not resize correctly). But in both
cases the code called is identical, the same div:

1) this resizes correctly:
    -  href="#userFormDivID" class="btn-green" data-lity>Add New User

   - userFormDivID is the top line of "user-profile-form.php":
  <div id="userFormDivID" style="overflow:auto; background:#f9f9f9; padding:20px; max-width:897px; width:897px; border-radius:6px; text-align:center; margin: 0 auto;" class="fonttx"> .....

2) This does NOT resize correctly:
  - href="user-profile-form.php?userId=new" class="btn-green" data-lity>Add New User
  - Again this is the same code in "user-profile-form.php" from #1 above

Again, I can not use method 1 because I need to pass parameters to the php file.

Thanks

**Comment by jsor** [comment]
Yes, because with method 2 you load the URL user-profile-form.php into an iframe. It is not possible to adjust the size with this method.
