### ISSUE TITLE
lity XSS Medium vulnerability

### ISSUE THREAD

**Issue by gregoryo** [jsor/lity#120]
hi jsor, 
thank you for the plugin.
we received a security alert from a scanning service for our use of lity on a website.

A  'non-persistent' or 'reflected' XSS vulnerability with 
```
<script> 
//var lightbox = lity(); 
lity('https:// ...
```
haven't had a chance to read the code to provide more information and a true bug report, but did want to let you know.
regards.

**Comment by jsor** [comment]
Thanks for the report. Since there is not much information provided, i'm closing for now. Feel free to repopen if you have more information available. Thanks!
