### ISSUE TITLE
Background opacity

### ISSUE THREAD

**Issue by chaiml** [jsor/lity#121]
Is there a way to set a CSS rule for the opacity of the background with affecting the opacity of the image itself?

If I set `opactiy:0.5` on the element `.lity.lity-opened` then also the image is set to half opacity.

**Comment by jsor** [comment]
No, you can't use `opacity`, thats why `rgba()` for the backgroudn color is used: https://github.com/jsor/lity/blob/master/dist/lity.css#L14
