### ISSUE TITLE
YouTube Related Videos

### ISSUE THREAD

**Issue by mharmon** [jsor/lity#123]
The script works great.  I'm having an issue removing the related videos from YouTube though.  

I'm doing the following without success:

<a href="//www.youtube.com/watch?v=XSGBVzeBUbk&rel=0" data-lity>iFrame Youtube</a>

I added the &rel=0 to the end of the URL and it still shows them.  Any help would be appreciated.

Michael

**Comment by inglesuniversal** [comment]
Michael: I also make use of lity script, and you are right, the related video feed shows afterwards no matter what. If there is a way for JSOR on finding a way to block that, it would be AWESOME. I also do enjoy the fact that NO ads pop up below the video during playback.

**Comment by jsor** [comment]
Adding `rel=0` to the URL correctly stops displaying related videos at the end for me.

```html
<a href="https://www.youtube.com/watch?v=XSGBVzeBUbk&amp;rel=0" data-lity>Play</a>
```

Note, that this seems to work only with the embed URL which i used in the Lity lightbox, not when appending it to the normal URL.

**Comment by zachschrock** [comment]
I'm was having this same problem as well, but was able to fix it. I added a rel=0 after line 216.

                    'https://www.youtube' + (matches[2] || '') + '.com/embed/' + matches[4],
                    $.extend(
                        {
                            autoplay: 1,
                            rel: 0
                        },
                        parseQueryParams(matches[5] || '')

**Comment by larsmqller** [comment]
https://www.youtube.com/watch?v=[YOUR ID]&amp;rel=0&amp;controls=0&amp;modestbranding=1&amp;&showinfo=0 worked for me.
