### ISSUE TITLE
Feature request - disable the esc key as an option

### ISSUE THREAD

**Issue by drye** [jsor/lity#124]
There are certain cases, where I would like to be in control of closing the lity dialog - for instance, when presenting a agreement, and the only way to close the lightbox would be to press a certain agree button, and not by pressing the ESC key.

Can disabling the ESC already be achieved? By looking at the code I don't see that it can.
Can disabling the ESC key be added as a feature?

**Comment by jsor** [comment]
No, unfortunately this isn't possible.

**Comment by drye** [comment]
Thanks for your answer, but just to clarify - is adding an option as a feature also not possible?

**Comment by jsor** [comment]
I've just release [v2.3.0](https://github.com/jsor/lity/releases/tag/v2.3.0) which adds a `esc` option. 

You can set that option via [.options()](https://github.com/jsor/lity#lityoptions) or per element.

```html
<a href="#modal" data-lity="{&quot;esc&quot;:false}"></a>
```
