### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Hakob-Martirosyan** [jsor/lity#125]
Hi, 
Could you please add some extra feature? 
I use #inline mode, and there are some cases when other js lib or code handles all clicks which has href="#SOME_ID" and after that - return false;  which affects your plugin functionality... popup window just didn't work (not opened). 
I'm already find the part of code which handles inline functionality and successfully changed to make it work. 

Here is the code 
target = opener.data('lity-target') || opener.attr('href') || opener.attr('src')

I change it to this, and get the target element from REL attribute, and got the functionality I want
target = opener.data('lity-target') || opener.attr('href') || opener.attr('src') || opener.attr('rel')

If you could put the opener.attr in options would be great. 

Thank you for very lightweight plugin and your hard work!!

P.S. 
Sorry for my bad English :)

**Comment by jsor** [comment]
This is easily done with the following code.

```js
$(document).on('click', '[data-lity-with-rel]', function() {
    lity($(this).attr('rel'), {}, this)
});
```

Then use the custom data attribute `data-lity-with-rel`.

```html
<button rel="img/sample.png" data-lity-with-rel></button>
```
