### ISSUE TITLE
Custom close button

### ISSUE THREAD

**Issue by EverThems** [jsor/lity#126]
Hey!
I would like a put on the one page for custom close button.

Its possible?

**Comment by jsor** [comment]
Yes, you can just add any element with a `data-lity-close`attribute inside the lightbox.

```html
<button data-lity-close>Close</button>
```

**Comment by EverThems** [comment]
Unfortunately, it does not work.

**Comment by EverThems** [comment]
I opening the iframe with pages. And i want custom closed button, on two different pages.

(I want the AD1 page on the button bg color black, and AD2 page on white bg color white, the button.)

**Comment by jsor** [comment]
That isn't possible from within an iframe. sorry See also #33

**Comment by SimonEast** [comment]
I was having an issue whereby a `<button>` with a `<span>` inside would not trigger the closing of the box. I removed the span and the issue resolved. Not sure why.

This code did NOT work:

```
<button type="button" class="close rt-close" data-lity-close aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
```

This code DID work:

```
<button type="button" class="close rt-close" data-lity-close aria-label="Close">
  &times;
</button>
```

**Comment by jsor** [comment]
That should work, could you setup a reproducible test case?

**Comment by franboud** [comment]
The event doesn't seem to bubble... If you have something in the button that has `data-lity-close`, it won't close. You have to add `data-lity-close` in the element inside the button (add it multiple times). Can this be fixed please?
