### ISSUE TITLE
onclick JS Example

### ISSUE THREAD

**Issue by airsoftsoldrecn9** [jsor/lity#129]
I would like to have lity open a lightbox by clicking on an object (video object, image object, button object) rather than an href link. My thought would be to do this with the JavaScript onclick parameter. Maybe something as follows:

```
<video id="sample" autoplay="" loop="" onclick="$(document).on('click', '[data-lightbox], lity);" data-autoclose="true" data-autoresize="fit">
	<source type="video/mp4" src="media/videos/example.mp4">
</video>
```

A concrete example would be great. One opening the original object in a lightbox. Maybe another opening a URL?

(My apologies if I am using the incorrect vernacular, and thank you very much for taking the time to read this!)

**Comment by jsor** [comment]
You could try something like this (i've omited non-relevant attributes etc.).

```html
<video data-lity data-lity-target="media/videos/example.mp4">
	...
</video>
```

**Comment by jsor** [comment]
Closing for now due to lack of feedback, feel free to reopen if needed.
