### ISSUE TITLE
Allow lightbox to scroll when the content is taller than the screen

### ISSUE THREAD

**Issue by jmedlin** [jsor/lity#13]
Is there a good way to allow the lightboxed content to scroll when the content is taller than the screen?

**Comment by jsor** [comment]
The content inside the lightbox should be scrollable. Could you setup a testcase where it is not?

**Comment by jmedlin** [comment]
Here is the project that I'm working on: http://toastmakerssupperclub.herokuapp.com/

**Comment by jsor** [comment]
Setting `overflow: auto` on the `#agegate` element should do the trick.

**Comment by jmedlin** [comment]
You da man.
