### ISSUE TITLE
YouTube Hide Info / Autoplay not working

### ISSUE THREAD

**Issue by onmarketing** [jsor/lity#131]
Hi,
 I added YouTube video embed link, I would like to remove info / adv / control but I have added rel=0&amp;showinfo=0&amp;controls=0 but seem not working.

<a class="play-btn fa fa-play" href="https://www.youtube.com/embed/iVtnv5wMqRQ?rel=0&amp;showinfo=0&amp;controls=0" data-lity></a>

Does anyone know about this?

Thanks,

Shaun.

**Comment by onmarketing** [comment]
I have added this one: https://www.youtube.com/embed/iVtnv5wMqRQ?rel=0&showinfo=0&controls=0

Still showinfo in the end video and control.

How do I fix this problem?

Thanks,

Shaun.

**Comment by jsor** [comment]
I cannot reproduce this, sorry.

**Comment by jsor** [comment]
Closing for now due to lack of feedback, feel free to reopen if needed.
