### ISSUE TITLE
Change height iframe on mobile (portrait)

### ISSUE THREAD

**Issue by jschor** [jsor/lity#133]
Hi there,

I use lity to show an url in an iframe (for a third party bookings module). Everything works fine, only on mobile (portrait) the height is of course very limited. Is there a possibility to make this larger so the lightbox covers (almost) the whole screen?

Changing .lity-iframe-container to padding-top:100% instead of 56.25% (only mobile breakpoint) makes is slightly higher but i don't know if this is a good solution. Maybe there is a better way to do it.

See it in action: [http://www.rtvevents.nl/volendams-artiestenweekend-2018.html](url) (Boek nu! button)

**Comment by jsor** [comment]
The iframe dimensions are 16/9 by default. There's no built in way to change that except that you could adjust the styles by overwriting it based on the `.lity-iframe` class.

**Comment by jschor** [comment]
Thanks for your reply Jan, 
Changing .lity-iframe-container to padding-top:120% instead of 56.25% (only mobile breakpoint), now works ok-ish:-). Do you think that's the best way to change the styling or can you think of another one?

**Comment by jsor** [comment]
If it works for you, then yes :)
