### ISSUE TITLE
Auto Open Lity Overlay

### ISSUE THREAD

**Issue by ayulayol** [jsor/lity#135]
How do i create auto open without clicking the links. Instead of clicking the link i want it auto popup. Is there away to do it?

**Comment by jsor** [comment]
See https://github.com/jsor/lity/tree/9c2510af0bce3163c40b374dd34938cc4f253922#example

**Comment by ayulayol** [comment]
i have created page http://ayulayol.html-5.me/sponsor/lityexample.html
let say i want to call button link youtube.js 
how do i create the java script?
sorry im still to javascript

**Comment by ayulayol** [comment]
<script>
var instance = lity('http://ayulayol.html-5.me/sponsor/youtube.fs.html');
var element = instance.element();
var opener = instance.opener();
Lity lity(string target, [Object options, [, HTMLElement|$ opener]]);
</script>

i try this code but t failed to popup.

**Comment by jsor** [comment]
Thats all you need:

```html
<script>
lity('http://ayulayol.html-5.me/sponsor/youtube.fs.html');
</script>
```

**Comment by ayulayol** [comment]
i already update and insert the code 
```
<script>
lity('http://ayulayol.html-5.me/sponsor/youtube.fs.html');
</script>
```
but it dosent work

**Comment by ayulayol** [comment]
doeshello any one know how to the the auto popup without clicking the link? please help me

**Comment by jsor** [comment]
Could you setup a minimal reproducible test case?

**Comment by ayulayol** [comment]
actually the question is simple how to do the auto popup lity?
nevermind i founf from someother website

it simple to create a simple script

`

<script type='text/javascript'>//<![CDATA[
--
  | window.onload=function(){
  | $(document).ready(function() {
  | setTimeout(function(){
  | lity('#advertisement');
  | }, 0);
  | });
  | }//]]>
  | </script>

`

<script type='text/javascript'>//<![CDATA[
--
  | window.onload=function(){
  | $(document).ready(function() {
  | setTimeout(function(){
  | lity('#advertisement');
  | }, 0);
  | });
  | }//]]>
  | </script>



before the head


example here http://ayulayol.html-5.me/lity/lityautopopup.html
