### ISSUE TITLE
No events get triggered

### ISSUE THREAD

**Issue by kontur** [jsor/lity#139]
Hey,

I seem to have a problem where no events get triggered and I don't exactly know why. The lightbox opens fine with below code, but none of the events get triggered:

```
$(document).on('lity:ready', function(event, instance) {
	console.log('Lightbox ready')
})

$(document).on('lity:close', function(event, instance) {
	console.log('Lightbox closed')
})

$(document).on('lity:resize', function(event, instance) {
	console.log('Lightbox resized')
})

$(document).on("click", "#place_order", function (e) {
	e.preventDefault()
	lity($("#checkout-licence-wrapper").html())
})
```

I use a browserify build chain and require lity as a module (stored to access via `lity` variable).

**Comment by jsor** [comment]
Maybe `document` isn't available as a global inside the bundle. Have you tried `window.document`?

**Comment by kontur** [comment]
I tried to debug this some more, but I am none the wiser.

`document` is available; the event listener opening lity is registered via `$(document).on`, inside the callback where lity is opened `document` is available, and in the source of lity just before the event gets triggered `document` is available.

I've checked inside lity before the `.trigger` calls what the respective `element` or `content` attributes are, and they should be matched. I even tried attaching event listeners to those returned elements, both in my code (does not work or react) and inside lity source (just to test, and the work there).

What could prevent those custom events from bubbling up to document?

**Comment by kontur** [comment]
Okay. It took a while of digging but it seems my browserify build system required and packages a jquery for lity, but for other plugins used the global jquery of Wordpress. I managed to define a proper shim for browserify so now als lity uses the same jquery (and the bundle doesn't include the extra jquery), and the events are caught.
