### ISSUE TITLE
I want `another link` enhancement

### ISSUE THREAD

**Issue by kntmrkm** [jsor/lity#14]
Thanks for cool and useful plugin.

I have an Idea.

When use low quality image for list.
After click image, use high quality image link.

I want use another image link for lity.

like below ...

```
<a href="https://example.com/low-quality-image.jpg" data-lity="https://example.com/high-quality-image.jpg">Image</a>
```

thanks.

**Comment by jsor** [comment]
This is already possible with the `data-lity-target` attribute.

```html
<a href="https://example.com/low-quality-image.jpg" data-lity-target="https://example.com/high-quality-image.jpg">Image</a>
```

**Comment by kntmrkm** [comment]
Thanks for quick response!

And sorry my poor attention.

:smile:

**Comment by jsor** [comment]
No problem, it's been undocumented. I've added documentation for it in 0aa17c45d716eb260f96a8c7633abab0b7bf990d.

**Comment by kntmrkm** [comment]
:+1:
