### ISSUE TITLE
Implement option to prevent closing the lightbox when clicking on the background

### ISSUE THREAD

**Issue by kontur** [jsor/lity#140]
I was wondering if an option to prevent closing the lightbox on background clicks would be something you'd be considering for this excellent plugin?

**Comment by jsor** [comment]
The only option is to use a custom template, see #132 or #12.

**Comment by kontur** [comment]
Okay, those seem viable options. I implemented it via event listeners to not react to certain clicks. Seems it could be a built in feature, though?

**Comment by jsor** [comment]
I'll try to keep Lity as lightweight as possible, there are enough full featured lightbox libraries out there. So, if you need something more powerful, Lity is probably not the right choice.

The question is, why would you prevent the user from closing the lightbox? You're probably trying to do some modal dialog or something with Lity. If yes, then Lity isn't the right tool for that.

**Comment by kontur** [comment]
I have a complex dialog with a licence that needs to be accepted (checkbox checked) before lity can be closed. You are right of course to keep the library light.
