### ISSUE TITLE
Implement option to prevent scrolling the document

### ISSUE THREAD

**Issue by kontur** [jsor/lity#141]
When you have a lity box that doesn't fill the entire screen it would be great to have a built in option to prevent scrolling that background (you get multiple scrollbars when the lity box content itself is overflowing).

I've now just added this snippet after the lity call, but this (or something more sophisticated) could go inside the library:

```
$("body").on("wheel", function (e) {
  if ($(e.target).is(".lity-wrap")) {
    e.preventDefault()
  }
})
```

**Comment by jsor** [comment]
You can simply do that via CSS too, eg:

```css
.lity-active body {
    overflow: hidden;
    height: 100vw;
}
```

Lity adds a `lity-active` class to the `html` element once a lightbox is open.

**Comment by kontur** [comment]
A, good to know the outermost tag receives the class change as well.
