### ISSUE TITLE
can not play youtube on ie8

### ISSUE THREAD

**Issue by smallma** [jsor/lity#143]
Hi, 

Lity is really a good tools for anything needs lightbox. recently we try to play youtube on ie8 by lity, but not work. can you help to fix it? Thank you.

**Comment by jsor** [comment]
Yes, but it's not Lity. It's the YouTube player itself that doesn't work with IE8.

**Comment by smallma** [comment]
Is there any solution? or we just leave IE8 from now?

**Comment by jsor** [comment]
> or we just leave IE8 from now?

This 👍
