### ISSUE TITLE
Issues opening Lity on page load - console error

### ISSUE THREAD

**Issue by demo38** [jsor/lity#147]
Hello - thank you for the Lity v2.2.2 script - it's a favorite go-to, but I've hit an issue getting it to auto-open on page load on a client site.

They are using an off-the shelf theme, so enqueuing Lity js and css through functions.php within a child theme, then conditionally init on the home page for some inline content.

A direct link is working to open Lity with the inline content, so I know the scripts are all loading as intended, but having issues getting the auto-load to fire.

Here is my auto load:
`<script>
    jQuery(document).ready(function($) {

        var lightbox = lity();
        lightbox('#inline');

        $( ".lightbox-close" ).click(function() {
          lightbox.close()
        });

    });
</script>`

But, upon load, I get this in console:

`Uncaught TypeError: Cannot read property 'preventDefault' of undefined
    at y (lity.min.js?ver=2.2.2:5)
    at HTMLDocument.<anonymous> ((index):413)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
y @ lity.min.js?ver=2.2.2:5
(anonymous) @ (index):413
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2`

Any thoughts on how to resolve? 

Thanks for your help,
Jonathon

**Comment by jsor** [comment]
You need to call `lity()` directly with the target.

```
var lightbox = lity('#inline');
```

**Comment by demo38** [comment]
Perfect - thank you for your help and the great script.
