### ISSUE TITLE
Images loaded by controller are displayed incorrectly  

### ISSUE THREAD

**Issue by Artu1000** [jsor/lity#15]
Hi,

First, thanx for your work. Your lightbox is excellent and I'm found of it.

I have a problem when I try to apply the lity lightbox on an image loaded on the fly by a controller.

I give you an example :
```
<a href="my-route-to-my-controller" data-lity>
<img src="...">
</a>
```

The image appears but for an image with 300 px height and 300px height, the iframe size is 964px by 542.25px.
That must be a clue, I get the following message in my console : Resource interpreted as Document but transferred with MIME type image/png: "my-route-to-my-controller"

Does your lity lightbox provide a way to display image loaded by this way correctly ?

Thank you for you attention.

**Comment by jsor** [comment]
Unfortunately not. The image handler checks for an image extension like `.jpg`. If you can't change the to `my-route-to-my-controller.jpg` i'm afraid it isn't possible with lity.

**Comment by Artu1000** [comment]
Ok, thanx, I'll manage my image differently (with symlinks to get access to them directly).
Keep up the good work !
