### ISSUE TITLE
Any way to make youtube videos play in HD quality by default?

### ISSUE THREAD

**Issue by ipoznyak** [jsor/lity#152]
Hi, is there a way to make youtube vids play in HD 720 or 1080p by default?

**Comment by jsor** [comment]
If i remember correctly, you can append `?vq=hd1080` or `?vq=hd720` to the URL.

**Comment by ipoznyak** [comment]
Doesn't seem to work. The videos open in SD

**Comment by jsor** [comment]
That only works for the embed URLs, Lity will transfer that parameter to the embed URL. And of course, the video itself must support that quqlity.

**Comment by ipoznyak** [comment]
Here is the URL I use: https://www.youtube.com/embed/B_o52vYomMw?vq=hd720&autoplay=1&modestbranding=1&rel=0&autohide=1&showinfo=0&controls=1&playsinline=1&webkit-playsinline=1&color=white

**Comment by jsor** [comment]
SInce this doesn't seem to an officially supported parameter, it probably doesn't always work. No sure to be honest, maybe a little googling helps.

**Comment by ipoznyak** [comment]
I see. Ok, one more question: How do I change the size of the lity-container? I want it to occupy more space on the screen.
