### ISSUE TITLE
The SVG image was not shown.

### ISSUE THREAD

**Issue by huukimit** [jsor/lity#154]
I used to make a light box for the SVG image.
But, some images could not show.
- The first image is OK:
![SVG OK](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/DroidSans.svg)
- The second image is not shown:
 ![SVG Failed](https://upload.wikimedia.org/wikipedia/commons/0/02/Linear_congruential_generator_visualisation.svg)

This is an [[example code]](https://codepen.io/huukimit/pen/XVXdmQ) that I used.
Please help me.

**Comment by jsor** [comment]
This happens probably to this check:
https://github.com/jsor/lity/blob/9c2510af0bce3163c40b374dd34938cc4f253922/src/lity.js#L147-L149

I think `naturalWidth` is 0 for svg's without a defined width/height (or set to `100%`). I have no immediate fix for this now. It probably needs some investigation and a workaround implemented for svg's.
