### ISSUE TITLE
Not really an issue but....

### ISSUE THREAD

**Issue by cowboysdude** [jsor/lity#157]
Is it possible to show video title under the video itself?

Huge thanks and great work.... I have it working on MagicMirror2 :+1: 

Also how can I change the X to CLOSE and move it outside the container?

**Comment by jsor** [comment]
> Is it possible to show video title under the video itself?

Not out of the box, but you could use the [open](https://github.com/jsor/lity/tree/2.x#lityopen) event to manipulate the content of the lightbox. 

> Also how can I change the X to CLOSE and move it outside the container?

Not sure what you mean here, the close button is already positioned outside the container.
