### ISSUE TITLE
Loading image dynamically

### ISSUE THREAD

**Issue by joho1968** [jsor/lity#158]
Not sure why, but I can't get it to work when href or data-lity-target is set to something like this:

https://server.com/path/to/php/script/showimage.php?tvsid=2287d84748a&txid=2010&tdon=15863%402379%26ajax%3Dfalse

If I load that URL in the browser directly, the proper image is displayed by Firefox. I can get lity working with plain .php files to load content into the "lightbox". It is af it doesn't even want to try loading it ...

Are there any particular HTTP headers the showimage.php script must output for lity to like the returned data?

It currently outputs

Content-type
Content-disposition
Content-transfer-encoding
Expires
Pragma
Cache-control

**Comment by jsor** [comment]
You could force the image handler with the `data-lity-handler="image"` attribute.

**Comment by joho1968** [comment]
Thanks for the suggestion. That did, however, not do the trick. I've now also tried with a static .jpg file that, when given the same URL, Firefox displays fine. I must (obviously) be doing something wrong.

**Comment by jsor** [comment]
Could you setup a reproducible test case?

**Comment by joho1968** [comment]
Try this, it does not behave like I would have expected it to:

https://tools.webbplatsen.se/lity.html
If you want to check the dynamic image loading, you can instead load https://tools.webbplatsen.se/test.php.

**Comment by jsor** [comment]
See https://github.com/jsor/lity/issues/158#issuecomment-358706555. I don't see that attribute in the `<a>`.

**Comment by jsor** [comment]
Also, https://tools.webbplatsen.se/test.php responds with the header `Content-Disposition: attachment; filename=ThisIsTheFilename.jpg` which forces the download dialog.

**Comment by joho1968** [comment]
Yes, I noticed the download vs inline too.
Is the data-lity-handler required?

**Comment by jsor** [comment]
> Is the data-lity-handler required?

Yes, otherwise Lity doesn't recognize theta URL as image.

**Comment by joho1968** [comment]
Yes, I noticed the download vs inline too.
Is the data-lity-handler required?

**Comment by joho1968** [comment]
OK
