### ISSUE TITLE
iframe external url

### ISSUE THREAD

**Issue by jasomdotnet** [jsor/lity#160]
Can I open using lity external url in iframe. Youtube video works, internal url works, but I cannot figure out how to open external url. Thank you.

**Comment by jsor** [comment]
Not sure, iFrames are the fallbacks and should work. Could you setup a reproducible test case?

**Comment by jasomdotnet** [comment]
I found out that there was a problem over https/http mixed content loading. Site with lity was on https and loaded iframe was on http. Consider this to be solved.
