### ISSUE TITLE
Help with URL 

### ISSUE THREAD

**Issue by iamteejay** [jsor/lity#164]
New to this, so much appreciation in advance. When I add all the files to the site and code to the page, everything works but the link to the content that is to appear in the light box. Even the demo page when on my site goes to this link:

http://www.mysite.com/lity-2.3.0/dist/https://player.vimeo.com/video/1084537?autoplay=1

Instead of 

https://player.vimeo.com/video/1084537?autoplay=1

I guess I need to remove something from the JS file, but I am not sure what. Any guidance would be much appreciated, please.

Thanks, Teejay

**Comment by jsor** [comment]
I would like to help, but i actually have to see some code :)

**Comment by iamteejay** [comment]
Hi Jsor, 

Thanks for checking back. I made an error with file referencing, and after a few attempts, I managed to get it working. So, sorry I did remove my inquiry after I resolved my own issue, but at least it gives me a moment to give you thanks for this sleek tool.

THANKS!

Teejay

**Comment by jsor** [comment]
Glad you solved it 👍
