### ISSUE TITLE
Inline Lightbox scrolls to top of the page

### ISSUE THREAD

**Issue by luiszayas** [jsor/lity#165]
I have replicated your inline Lightbox. When I click on the link to open the Lightbox, the page scrolls to the top in the background and when I close the Lightbox I am back at the top of the page. This doesn't happen when I create a youtube Lightbox.

**Comment by jsor** [comment]
Could you setup a reproducible test case?

**Comment by luiszayas** [comment]
Sorry but I am now using bootstrap modals for this type of content. Still using Lity for youtube Lightbox though. Thank you!

**Comment by tridoan** [comment]
Im having the same issue when using inline Lity lightboxes 2.2.2

**Comment by ScotsScripts** [comment]
Same here, when the inline lightbox opens the content behind it scrolls to the bottom, in my case. I'm setting a slightly opaque background so it can act as a traditional modal, however it's not really working since the original content doesn't stay in the same place.
