### ISSUE TITLE
Button doesn't close on click

### ISSUE THREAD

**Issue by franboud** [jsor/lity#176]
I noticed that a button with content (for instance, with a `<span><svg>`) doesn't close the Lity lightbox on click, even with the data-lity-close attribute. This is to prevent from closing the lightbox when you click inside of it. This makes sense. But, how can you bypass this on a button?

Here's my solution:
I made another attribute, named [data-lity-force-close].

In the lity.js file, add those lines after the line 562:
`.on('click', '[data-lity-force-close]', function(e) {
                self.close();
            })`

Now, you can add a button with content in it and the attribute data-lity-force-close and it will actually CLOSE the lightbox... way to go!

**Comment by jsor** [comment]
This is currently a limitation, yes. Your workaround is indeed one way to solve this. It can be generalized without hacking the core. Just put that anywhere on your page:

```js
$(document).on('lity:open', function(e, instance) {
    instance.element().on('click', '[data-lity-force-close]', function() {
        instance.close();
    });
});
```

**Comment by franboud** [comment]
Works like a charm! Thanks!
