### ISSUE TITLE
Feature request: Internationalisation

### ISSUE THREAD

**Issue by RavanH** [jsor/lity#177]
A very interesting light weight script like this should be available to everybody around the world. This means: texts like "loading..." and "esc to close" etc. should be translatable. And if possible, language selection should adhere to the document html lang attribute.

Or maybe just an easier way to pass alternative text (or html?) as options? It seems using the template parameter is a bit overkill...

**Comment by jsor** [comment]
I always felt it is quite easy to do that with the template option. If you have a good idea how to handle that, i'm open for a patch...

**Comment by marcelogarbin** [comment]
How can I translate if I am calling the files directly from node_modules?

**Comment by RavanH** [comment]
@marcelogarbin like @jsor said, currently there is only the template option. For example, I'm doing this 
to set a global template with French texts:
`
jQuery(function(){
	lity.options(
		'template', '<div class="lity" role="dialog" aria-label="Fenêtre de dialogue (Appuyez Échap pour fermer)" tabindex="-1"><div class="lity-wrap" data-lity-close role="document"><div class="lity-loader" aria-hidden="true">Chargement...</div><div class="lity-container"><div class="lity-content"></div><button class="lity-close" type="button" aria-label="Fermer (Appuyez Échap pour fermer)" data-lity-close>&times;</button></div></div></div>'
	);
};
`

**Comment by marcelogarbin** [comment]
Thank's @RavanH
