### ISSUE TITLE
Simple question about Lity!!!

### ISSUE THREAD

**Issue by inglesuniversal** [jsor/lity#189]
IF I have a function like this...

        function contacts(){
        var lightbox = lity('/mysite.com/mobilecontacts.php');
        }

How do I get that iframe or window to appear with border_radius set as GLOBAL default to n (number) of pixels... By dafault lity makes the external links to appear in a totally square box.

Thanks so much for your GREAT help

Hugo

**Comment by trijste** [comment]
Can't you edit the Lity css file to change how the lightbox presents content?
