### ISSUE TITLE
Inline content

### ISSUE THREAD

**Issue by ronnsson** [jsor/lity#20]
Hey!
Great plugin! I just had one question however. I want to use the inline function for a couple of different explanatory textfields. The ID messes with this however since they are being used on the same page. Do you have any pointers here? 

Cheers,
Ronny

**Comment by jsor** [comment]
Not sure what the actual problem is since lity doesn't duplicate the inline content. Could you maybe setup a reproducible test case on jsfiddle or similar to illustrate the problem?

**Comment by ronnsson** [comment]
I'm having a bit of trouble running the fiddle with lity at all but you can see the markup at least. 
https://jsfiddle.net/dmLdohdo/

**Comment by jsor** [comment]
ok, i see now? Can't you just use different id's?
```html
<a href="#inline-1" data-lity>
  <p>i</p>
</a>
<div id="inline-1" class="lity-hide">
  <p>Test1</p>
</div>

<a href="#inline-2" data-lity>
  <p>i</p>
</a>
<div id="inline-2" class="lity-hide">
  <p>Test2</p>
</div>
```
