### ISSUE TITLE
Hiding the original close button

### ISSUE THREAD

**Issue by ronka** [jsor/lity#202]
Hey, Is there any way to hide the original close button and instead putting a custom one? for example i want the close button to be in the popup(top right corner).
i know i can hide the close button with css, but in case i dont want it in the DOM at all.

**Comment by LewdNeko** [comment]
What's wrong with having it in the dom at all? Hiding it can't be too hard...

**Comment by SebastienCruz** [comment]
You can also change the css directly. It's quite easy and you can do whatever you want with it...

**Comment by ronka** [comment]
I didnt want to edit the plugin original files and have i wanted to have a clean dom.

just thought that hiding/replacing the close button would be a good feature.

**Comment by LewdNeko** [comment]
Yeah you can remove it from the template entirely. You could also listen for lity:open and just `$('.lity-close').toggle()`

**Comment by SebastienCruz** [comment]
With jQuery it's pretty easy :
`$('.lity-close').remove();`

Or if you want to modify it : 

```
var newbutton="<img src='your/img/button.png' alt='Close' class="lity-close" type="button" aria-label="Close (Press escape to close)" data-lity-close/> ";
$('.lity-close').html(newbutton);
```


I just see Neko's solution, it works too...

**Comment by jsor** [comment]
The "proper" way would be to use a custom `template`.

https://github.com/jsor/lity/blob/7c3162be6238c80c9df59ea5dc48169aef2efc2f/src/lity.js#L38

If you just want to change the position, use `position: absolute`, see comment at:
https://github.com/jsor/lity/blob/7c3162be6238c80c9df59ea5dc48169aef2efc2f/src/lity.less#L133-L134

**Comment by ronka** [comment]
> The "proper" way would be to use a custom `template`.
> 
> [lity/src/lity.js](https://github.com/jsor/lity/blob/7c3162be6238c80c9df59ea5dc48169aef2efc2f/src/lity.js#L38)
> 
> Line 38 in [7c3162b](/jsor/lity/commit/7c3162be6238c80c9df59ea5dc48169aef2efc2f)
> 
>  template: '<div class="lity" role="dialog" aria-label="Dialog Window (Press escape to close)" tabindex="-1"><div class="lity-wrap" data-lity-close role="document"><div class="lity-loader" aria-hidden="true">Loading...</div><div class="lity-container"><div class="lity-content"></div><button class="lity-close" type="button" aria-label="Close (Press escape to close)" data-lity-close>&times;</button></div></div></div>' 
> If you just want to change the position, use `position: absolute`, see comment at:
> [lity/src/lity.less](https://github.com/jsor/lity/blob/7c3162be6238c80c9df59ea5dc48169aef2efc2f/src/lity.less#L133-L134)
> 
> Lines 133 to 134 in [7c3162b](/jsor/lity/commit/7c3162be6238c80c9df59ea5dc48169aef2efc2f)
> 
>  // Change to position: absolute to display close button inside content container 
>  position: fixed;

Didn't know about the template property. thanks 👍

**Comment by nickjacobs** [comment]
How do you use the template - there is nothing in the docs ???
