### ISSUE TITLE
Add support for HTML5 video

### ISSUE THREAD

**Issue by sorcamarian** [jsor/lity#205]
Would be great if a html5 `<video>` element could be used with the lightbox .
At the moment, if a local URL is added, a `<iframe>` is created, just as for a YouTube video.

**Comment by helloromero** [comment]
+1

**Comment by Renrhaf** [comment]
+1

**Comment by milesw** [comment]
You can set this up pretty easily with a custom handler. Lity will run your handler just before the lightbox is opened.

**Basic example:**
```javascript
lity.handlers('video', (target) => {
  if (typeof target === 'string' && target.indexOf('.mp4') > 0) {
    return `
      <video style="max-width: 100%;" autoplay playsinline>
        <source src="${target}" type="video/mp4">
      </video>
    `;
  }
  return false;
});
```

**Comment by jsor** [comment]
Thanks @milesw, that's the way to go 👍
