### ISSUE TITLE
Am I seeing double? Duplicate instances of Lity.

### ISSUE THREAD

**Issue by iversoncreative** [jsor/lity#209]
When opening an image in Lity, I seem to be seeing two instances of the enlarged image. I have to click twice to close it and see the animation twice as well. What might cause this?

**Example**: https://www.patrickiverson.com/portfolio/lux-writes/

**View Source**: 
![screen shot 2019-02-15 at 12 45 26 pm](https://user-images.githubusercontent.com/3998792/52880629-ad22d880-311f-11e9-9c2a-679ea195fc51.png)

**Comment by jsor** [comment]
You're probably loading and applying lity twice on the page. I've seen lity is included in both `/wp-content/themes/clean2019/dist/scripts/main-6b986a9ffc.js` and `/wp-content/themes/clean2019/dist/scripts/loadmore.js`.

**Comment by iversoncreative** [comment]
Bingo. I rechecked my build process and in fact was doing this. Fixed that and am no longer seeing double lity. Thank you for takin the time to check it out. Very much appreciated.
