### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by WideCircle** [jsor/lity#21]
Hi there!
What is the browser support for this very nice plugin?
I've been able to test for older versions of FF & Chrome & there it works really nice.
This doesn't really come as a surprise though.. :-)
How is the support for IE?
Since I can't run IE versions side by side I've tried it with choosing older version of IE, version 9, inside IE11. It seems to be working fine except it crashes when tring to close the Vimeo iFrame. But it's hard to know if this is really happening in IE9 for real...
Thanks for a nice plugin...

**Comment by jsor** [comment]
Lity supports IE down to IE8 although without the CSS transitions.

**Comment by WideCircle** [comment]
Thanks for a swift reply!
Sorry - I realised that I've already asked this question before & got an answer from you then as well. :-)
