### ISSUE TITLE
Autoplay not working in Chrome

### ISSUE THREAD

**Issue by bradley2083** [jsor/lity#213]
As it stands, when I click either the Youtube or Vimeo links in your demo they open but do not autoplay (in Chrome). They seem to work in Safari and FF. 

Was searching around and it seems that the common update required for video to autoplay in Chrome is to have allow="autoplay" in the iframe embed.  I've changed the following in your lity.js file:

`function iframeHandler(target) {
        return '<div class="lity-iframe-container"><iframe frameborder="0" allowfullscreen src="' + target + '"/></div>';
    }`

to:

`function iframeHandler(target) {
        return '<div class="lity-iframe-container"><iframe allow="autoplay" frameborder="0" allowfullscreen src="' + target + '"/></div>';
    }`

and that seemed to work for both Youtube and Vimeo.  Any way to test on your end and potentially add this as an update?  

Thanks for taking the time to create this plugin btw!

**Comment by bportman** [comment]
+1

**Comment by rocketedaway** [comment]
+1

**Comment by navneet29** [comment]
Video should be muted for autoplay to work. Autoplay will not work, if you dont set mute true.

**Comment by sntran** [comment]
As @navneet29 said, #222 is not enough for autoplay to work. You also need to make it muted. Vimeo uses `?muted=1` querystring, and I think YouTube also has similar configuration.

**Comment by sectsect** [comment]
@sntran 

You can add YouTube Parameters to url.

```html
<a href="https://www.youtube.com/embed/-_Lw6WXsUnM&autoplay=1&mute=1" data-lity>iFrame Youtube</a>
```

**Comment by baxeico** [comment]
In my case mute=1 was not necessary, just use this as href:

```
<a href="https://www.youtube.com/embed/<YOUTUBE_ID>?autoplay=1" data-lity>iFrame Youtube</a>
```
