### ISSUE TITLE
CSS versioning issue - breaking videos

### ISSUE THREAD

**Issue by timostsauber** [jsor/lity#214]
There seems to be a versioning issue with the css files?
The version on GitHub doesn't match the CDN version.

https://github.com/jsor/lity/blob/master/dist/lity.css
!=
https://cdnjs.cloudflare.com/ajax/libs/lity/2.3.1/lity.css

The version on github is missing the video iframe classes from around 168 onwards.

And it results in the video not being sized correctly and not visible when launched : (

The CDN version works as expected though, if anyone else is experiencing the same issue.

**Comment by jsor** [comment]
The master branch contains the upcoming version 3.0, use the [2.x](https://github.com/jsor/lity/tree/2.x) branch,
