### ISSUE TITLE
"×" should be "&times;"

### ISSUE THREAD

**Issue by joshuajameshunt** [jsor/lity#22]
I ran into an issue where the "×" symbol to close the lightbox was being misinterpreted by the browser as "Ã–" (Safari) so I propose changing it to the HTML entity "&times;" in the JavaScript.

**Comment by jsor** [comment]
Thanks for the report, care to file a PR?

**Comment by fourroses666** [comment]
I like lity, thanks for that jsor. 
Made a pull for this minor issue;
https://github.com/jsor/lity/pull/32

**Comment by jsor** [comment]
Released in [v1.6.5](https://github.com/jsor/lity/releases/tag/v1.6.5).

**Comment by shlomnissan** [comment]
Love Lity buddy, thanks! Just a heads up, this issue still seem to appear. Had to change 'x' to &times; myself.
