### ISSUE TITLE
A cookie associated with a cross-site resource at http://youtube.com/ was set without the `SameSite` attribute. 

### ISSUE THREAD

**Issue by iwasherefirst2** [jsor/lity#231]
When I open a youtube video with lity I get in the console this error:

> A cookie associated with a cross-site resource at http://youtube.com/ was set without the `SameSite` attribute. 

This seems to happen on the demo version aswell.

That is the output of the console from https://sorgalla.com/lity/ after clicking the youtube button

![grafik](https://user-images.githubusercontent.com/1765602/70210872-0c47ed00-1734-11ea-8d70-73ed368842f4.png)

**Comment by jsor** [comment]
That's nothing related to lity but coming from youtube.com when the iframe is loaded.
