### ISSUE TITLE
data-lity-desc still available??

### ISSUE THREAD

**Issue by ranchmed** [jsor/lity#238]
The website documents a caption capability using data-lity-desc. When I click the demo on the website, I don't see a caption even though the source code indicates I should. I have done a quick search of the lity source code, and don't find this variable. Am I missing something, or has this functionality not available?

**Comment by jsor** [comment]
This is not meant for a visible caption but for the `alt` attribute of the `<img>` element to improve accessibilty.

```html
<img src="https://farm9.staticflickr.com/8642/16455005578_0fdfc6c3da_b.jpg" alt="Photo of a flower" style="max-height: 339px;">
```
