### ISSUE TITLE
Wrong size if image is embedded as base64 data

### ISSUE THREAD

**Issue by kaju74** [jsor/lity#25]
I love this lib and it works fine if you use physical based images...but as soon as I try to link to an base64 image data, the window will opened up (displaying the image) but not auto-fit the image dimensions (instead, it is full-size).

Any idea how to solve this?

Regards,
kaju

**Comment by jsor** [comment]
Thanks for the report, it's fixed and released in [v1.6.2](https://github.com/jsor/lity/releases/tag/v1.6.2).

The problem was, that the data URI wasn't detected correctly and the image was shown in an iFrame.

**Comment by kaju74** [comment]
Wow - that was a fast fix and it works very well. Thank you ;-)

**Comment by jsor** [comment]
Glad it works now.
