### ISSUE TITLE
npm/browserify jquery

### ISSUE THREAD

**Issue by coreyworrell** [jsor/lity#26]
Lity requires jQuery when using npm/browserify, but if my site already uses a CDN version of jQuery, I can't use lity without including jQuery twice. Is there a solution? Thank you.

**Comment by jsor** [comment]
Use `--external`: https://github.com/substack/node-browserify#usage

**Comment by coreyworrell** [comment]
@jsor I don't want the CDN version included in my bundle though. It will be included using a separate script tag.

**Comment by jsor** [comment]
Some googling brought up [browserify-shim](https://github.com/thlorenz/browserify-shim/tree/master/examples/shim-jquery).

**Comment by coreyworrell** [comment]
Yes, I have found that, but it does not seem to be working. May have to open a ticket with them I suppose. Thank you.

**Comment by coreyworrell** [comment]
Just for future reference, I found that I need to specify the browserify-shim transform as a global transform, which cannot be done via package.json configuration options, but rather through the browserify CLI or JS api.

IE:
package.json
```json
"browserify-shim": {
  "jquery": "global:jQuery"
},
"scripts": {
  "js": "browserify -g browserify-shim index.js -o bundle.js"
}
```
Thanks for your time @jsor

**Comment by jsor** [comment]
Great, glad you solved it.
