### ISSUE TITLE
Close function fails after hitting enter while open (keyCode 13)

### ISSUE THREAD

**Issue by Wachem** [jsor/lity#29]
Hi!

The close function seems to fail when you open a YouTube video and hit 'enter' while it's open. Probably it has something to do with the var "_instance".

All the best,
Wachem

**Comment by jsor** [comment]
Thanks for the report. I released [v1.6.4](https://github.com/jsor/lity/releases/tag/v1.6.4) which fixes this issue.

**Comment by Wachem** [comment]
Super! Thanks alot ;)
