### ISSUE TITLE
Lightbox opening up at lower left bottom of page

### ISSUE THREAD

**Issue by PaulTuraew** [jsor/lity#31]
Hi,

I used Bower to install Lity in my Wordpress site but when I click the link, there is no lightbox effect. The video simply opens up and begins to play at the very bottom left part of the page (I have to scroll to see it). It is also about 1/5 the correct size. 

Here is my code (I am also using Bootstrap), any help to get this to appear correctly in the center of the page with the darkened background would be greatly appreciated.

```
<div class="row">
  <div class="container videos">

    <div class="col-md-5 col-md-offset-1 first-video">
      <h3>Sample Featured Video</h3>
      <a href="https://www.youtube.com/watch?v=L5L5j9qqmXI" data-lity><img src='/wp-content/themes/sage-8.4.2/assets/images/blog_video1.jpg' class="img-responsive center-block"></a>
    </div>
    <div class="col-md-5">
      <h3>Sample Featured Video</h3>
      <a href="#" data-lity><img src='/wp-content/themes/sage-8.4.2/assets/images/blog_video2.jpg'  class="img-responsive center-block"></a>
    </div>

  </div><!--end watch-more-->
</div><!--end row-->
```

**Comment by jsor** [comment]
That sounds like the CSS is missing. Ensure that the [CSS file](https://github.com/jsor/lity/blob/master/dist/lity.css) is loaded.

**Comment by PaulTuraew** [comment]
Thank you, you were right. For whatever reason, Bower was not allowing the CSS to load. I manually installed the CSS and works fine.
