### ISSUE TITLE
Add addition URL parameters to YouTube links

### ISSUE THREAD

**Issue by phwconz** [jsor/lity#34]
UPDATE: Sorry, you can ignore this. I made an error in my original youtube.com/watch?.. URL which led me to using the embed URL. My mistake sorry.

------------------------

Thanks for making Lity! I'm enjoying using it and have a question with regards to using additional YouTube URL parameters.

I see that Lity generates a YouTube URL from the href and appends 'autoplay=1' to it, i.e.: 
=> www.youtube.com/embed/oJX4TcyhkP0?autoplay=1

I'm wanting to use the additional parameters 'showinfo=0' and 'rel=0'. In order to have this work with Lity, I need to make the href:
=> www.youtube.com/embed/oJX4TcyhkP0&showinfo=0&rel=0

so that the resulting URL becomes:
=> www.youtube.com/embed/oJX4TcyhkP0?auotplay=1&showinfo=0&rel=0

Problem is, this href [www.youtube.com/embed/oJX4TcyhkP0&showinfo=0&rel=0] is invalid as the first parameters starts with '&' instead of '?' and if anyone grabs this URL directly, YouTube returns an error. 

Is there an easy way to pass these additional parameters?

**Comment by jsor** [comment]
Great you solved it (and thanks for using Lity :))!
