### ISSUE TITLE
adding title and small description

### ISSUE THREAD

**Issue by hardeepkgill** [jsor/lity#37]
Hi,

Can we add title and small description when opening image, video in lightbox.
something like this, data-title="Tile" AND data-desc="Small description goes here"
Let me know if this is possible or you can add this feature in near future?

**Comment by jsor** [comment]
This is not possible out of the box (and i'm not planning to add such a feature). But you can implement that yourself.

```javascript
$(document).on('lity:ready', function(event, $lightbox, $triggeringElement) {
    $lightbox.find('.lity-content').append('<h2>' + $triggeringElement.data('title') + '</h2><p>' + $triggeringElement.data('desc') + '</p>');
});
```

**Comment by hardeepkgill** [comment]
Thank you very much, it works !!!

**Comment by SimonKese** [comment]
Thank you, just one question. Where do i have to copy this script? Into the lity.js ? What position in there?

After that i can use it like this? 
 <a href="//vimeo.com/1896xxxxx" data-lity data-title="TESTEST" data-desc="testest">

Thanks a lot for your help!

**Comment by jsor** [comment]
This is just a customization and should go anywhere in your own scripts.

**Comment by nsrosenqvist** [comment]
This is broken for me when I try to use it. The error says that $triggeringElement is undefined. Is this still a working solution?

**Comment by jmelendev** [comment]
@nsrosenqvist,

Months late but figured i'd post for anyone else who inquires. I was able to make it work with this

```
        var lity = $('.single-post-image').find('.fsThumbnail img');

        lity.attr('data-lity', '');

        $(document).on('lity:ready', function(event) {
          var caption = $('<p>' + lity.attr('alt') + '</p>');
          caption.appendTo($('body').find('.lity-content'));
        });
```

**Comment by maxattack** [comment]
An update to @jsor's original snippet:

`$(document).on('lity:ready', function(event, $lightbox) {
    $triggeringElement = $lightbox.opener();
    $lightbox.find('.lity-content').append('<h2>' + $triggeringElement.data('title') + '</h2><p>' + $triggeringElement.data('desc') + '</p>');
});`

**Comment by JanKups** [comment]
An update:

`$(document).on('lity:ready', function(event, $lightbox) {
    var $triggeringElement = $lightbox.opener();
    $('.lity-content').append('<h2>' + $triggeringElement.data('lityTitle') + '</h2><p>' + $triggeringElement.data('lityDesc') + '</p>');
});`

**Comment by MMelrose** [comment]
So.. I know this thread is closed, but I'm trying to make this work in a Squarespace site, the basic lightbox itself works beautifully, but my limited knowledge of coding is leaving me a bit stuck. I have the updated code from @JanKups...

`$(document).on('lity:ready', function(event, $lightbox) {
    var $triggeringElement = $lightbox.opener();
    $('.lity-content').append('<h2>' + $triggeringElement.data('lityTitle') + '</h2><p>' + $triggeringElement.data('lityDesc') + '</p>');
});`

and on the link I have this code (revised from @SimonKese)...

`<a href="//vimeo.com/1896xxxxx" data-lity data-lityTitle="TESTEST" data-lityDesc="testest">`

so where am I going wrong?

Thanks in advance.

**Comment by pleaj** [comment]
Hello Jan,

im trying to figure it out myself but im stuck. Ive added the updated code to the .js file and "data-lity data-lityTitle="TESTEST" data-lityDesc="testest"" to the html tag but it returns "Cannot GET /undefined".

Where am i going wrong? 

Thanks!
