### ISSUE TITLE
How to add soemthing to the close trigger.

### ISSUE THREAD

**Issue by nextgenthemes** [jsor/lity#4]
Sorry for abusing the issue tracker for this question. I am not so experienced with JavaScript.

```
	$(document).on( 'click', '[data-lity-close]', function(event) {
		
		$( '[data-arve-lightbox]' ).removeAttr( 'src data-arve-lightbox' );
		
		$( '#wpadminbar' ).removeClass( 'arve-hidden' );
	});
```

I have this code and its works fine as long as the user clicks the close button, but it does not on ESC press. How could I hook into this event as well?

**Comment by jsor** [comment]
You should listen to the `lity:close` event lity triggers:

```javascript
$(document).on('lity:close', function() {
    $( '[data-arve-lightbox]' ).removeAttr( 'src data-arve-lightbox' );
    $( '#wpadminbar' ).removeClass( 'arve-hidden' );
});
```

There is also the corresponding `lity:open` event.

**Comment by nextgenthemes** [comment]
Ah that was easy, thanks to much also for mentioning the open even I will use it now as well.

**Comment by iandickety** [comment]
+1. This makes the plugin complete and exactly what I was looking for, thank you. Please add it to your docs!

**Comment by jsor** [comment]
Added to the [Readme](https://github.com/jsor/lity#events) in 2e2fbd5c428ea34db10b56e45be0307508e128b8.
