### ISSUE TITLE
Default quality Youtube

### ISSUE THREAD

**Issue by shortwoodBE** [jsor/lity#40]
Hi There,

Is there any way I can force the iFrame for a YouTube video, to use the highest possible quality? (Or at least start at 720p)

Kind regards,
Philippe

**Comment by jsor** [comment]
I think, YouTube tries to autodetect the best quality. But i [found](http://stackoverflow.com/questions/7582336/force-youtube-embed-to-start-in-720p) [some](http://stackoverflow.com/questions/10229114/youtube-how-to-force-480p-video-quality-in-embed-link-iframe) [articles](http://stackoverflow.com/questions/5001299/how-to-embed-high-quality-video-with-new-youtube-iframe-style-code) which suggest you can append a `vq` parameter to the URL to define the quality.

**Comment by shortwoodBE** [comment]
Ok Thanks for your time.
