### ISSUE TITLE
Responsive height?

### ISSUE THREAD

**Issue by rquast** [jsor/lity#42]
How can you set the window height to 95% no matter what the width is? Using something like flexbox?

**Comment by jsor** [comment]
No idea, to be honest. Sorry. Maybe anyone else has an idea.

**Comment by rquast** [comment]
I just figured out one approach. For my iframe, I wanted 100% width and height.. so for height I used css3 for setting height in lity.css with..

height: 100vh;

Most browsers support it and those that don't you can use modernizr to polyfill.

**Comment by jsor** [comment]
👍
