### ISSUE TITLE
x button on the top of lity-content

### ISSUE THREAD

**Issue by koolcocaleaf** [jsor/lity#45]
Hi,

How can I change code to move x button from the top of the page to appear on the top of the content (ex. iframe, img etc.?)

**Comment by jsor** [comment]
See https://github.com/jsor/lity/blob/master/src/lity.less#L133

**Comment by jsor** [comment]
Closing, feel free to reopen if you have further questions.

**Comment by cfukai** [comment]
Link is broken. I think this is current: https://github.com/jsor/lity/blob/2.x/src/lity.less
