### ISSUE TITLE
programmatic not working in Firefox

### ISSUE THREAD

**Issue by iamdavehj** [jsor/lity#48]
Hi, thanks for providing this code it's really useful. I'm using the following on my squarespace site:

in the header:
`var lightbox = lity();`

on each link:
`javascript:lightbox('VIMEO URL HERE');`

it's working fine in Safari and Chrome but in Firefox I get the following error message:

function popup(event) { "use strict"; // If not an event, act as alias of popup.open if (!event.preventDefault) { return popup.open(event); } var el = $(this); var target = el.data('lity-target') || el.attr('href') || el.attr('src'); if (!target) { return; } var options = el.data('lity-options') || el.data('lity'); if (open(target, options, el)) { el.blur(); event.preventDefault(); } }

I'm not sure what the problem is, can anyone help?

the site is www.treetop.tv

many thanks
Dave

**Comment by jsor** [comment]
Try using the `onclick` instead of the `href` attribute.

**Comment by iamdavehj** [comment]
thanks for the quick reply. Unfortunately I'm limited in Squarespace as to how I can add links to images. It only lets me use a regular `href` or the javascript code above.

**Comment by jsor** [comment]
What about using normal href's and delegated events?

```html
<a class="image-slide-anchor content-fill" href="https://vimeo.com/161936072">
```
```javascript
$(document).on('click', '[href*=vimeo.com]', lity());
```

**Comment by iamdavehj** [comment]
thanks again for the quick response. So if I understand correctly do I just put a regular href in the link box in Squarespace and then the second line of code

`$(document).on('click', '[href*=vimeo.com]', lity());`

in the footer or header?

**Comment by iamdavehj** [comment]
I've got it to work by putting the following code in the footer

` $('a[href^="https://vimeo.com"]').on('click', lity());`

thanks again for your help 👍

**Comment by jsor** [comment]
Yes, that's similar and should work 👍
