### ISSUE TITLE
(Not Issue) - I'm incompetent :( 

### ISSUE THREAD

**Issue by pn1gh2** [jsor/lity#49]
Hi there

I'm learning JS when on school break. Honestly, I still need tons of works to achieve my goal.

I'm building simple site for school project. In it, I use Magnific Popup JS as lightbox for all image formats (jpg, png ...). 

```js
jQuery(document).ready(function() {
	jQuery("a[href$='.jpg'], a[href$='.jpeg'], a[href$='.gif'], a[href$='.png']").magnificPopup({
		type: 'image',
		disableOn: function() {
			if( jQuery(window).width() < 300 ) {
				return false;
			}
			return true;
		}
	})
});
```

After I found out Lity, I really want to switch from Magnific Popup to Lity. Could you please help me to point out how I can add Lity on all image formats on my site?

Thanks much indeed.

**Comment by jsor** [comment]
Hi,

the same behaviour with lity:

```js
jQuery(document).on('click', "a[href$='.jpg'], a[href$='.jpeg'], a[href$='.gif'], a[href$='.png']", function(e) {
    if (jQuery(window).width() < 300) {
        return true;
    }

    lity.call(this, e);
});
```

**Comment by pn1gh2** [comment]
@jsor - Thank you very much! 

Learned something this evening. Precious. I do appreciate it.
