### ISSUE TITLE
How to add loading message and disable click outside

### ISSUE THREAD

**Issue by donenvy** [jsor/lity#5]
Hi I like your lightbox, I found it is responsive and not over bloated. I have a few questions if you wouldn't mind.

1. I can see a loading message in the script, but my javascript is not that good, so wanted know how can I enable the loading message everytime a iframe is being loaded? At the present moment the screen is blank till the iframe loads

2. How to disable clicking outside of iframe to close.

**Comment by donenvy** [comment]
Ok so looks like it was some css and js editing. Without editing the js file. I added the options to
template: '' and removed the data-lity-close attr from the litly-wrap and made the content css transparent so can see the loading message. So all is almost there except one problem, there is a big time gap between the loading message being removed and the iframe being displaying 2-3 seconds delay.

Is there anyway to get the loading message to disappear only when the iframe is loaded?

**Comment by jsor** [comment]
No, sorry. The iFrame is added instantly and loads. You would have to have the loading message inside the iframe.

**Comment by donenvy** [comment]
cool what about making the iframe fullscreen, whilst most other plugins can run 
style="border: 0; position:fixed; top:0; left:0; right:0; bottom:0; width:100%; height:100% 
to make it full screen, thats not working here and there seems to be automatic resizing taking place via js

**Comment by jsor** [comment]
That's not possible unfortunately. IMHO, you could just open a new window/tab in this case ;)
