### ISSUE TITLE
force use image handler

### ISSUE THREAD

**Issue by ssttevee** [jsor/lity#50]
The regexp test for the image handler prevents using an image url that does not have an image extension even if use `{'handler':'image'}` for the options.

i.e. I can't use images like https://lh3.googleusercontent.com/JT9YU8YgAur2EWr2-Ra1SFEqYjlqjH0q_GAimejTXK_hvxEEvymMsf1drGorDwsk9Js_Gf9H9ifCUOgUg3q-lhhk3w6FdnSg

**Comment by jsor** [comment]
Yes, good catch. I'm afraid this isn't possible at the moment. The handlers should be separated into a `test()` and `handle()` part so that `handle()` can be forced without checking the url.

I'm going to implement that for 2.0.
