### ISSUE TITLE
loading page as ajax request

### ISSUE THREAD

**Issue by Studioartcz** [jsor/lity#51]
Hi,

is some option to load page with ajax request? 
In framework what i am using is function to detect ajax request and i can overload page styles to "naked style". 

Idea: 

1)If i click to button where is link to page with parameter "?nostyle=true" lightbox load page via ajax and my system overload styles for lightbox view (without header, footer, etc - naked)..

2) If i click to same button but open link in new window / tab, page was with standart styles (with header, footer etc).

It's possible?

Thanks

**Comment by jsor** [comment]
No, sorry. Lity doesn't support loading contents via ajax.
