### ISSUE TITLE
Gallery group

### ISSUE THREAD

**Issue by Studioartcz** [jsor/lity#53]
Hi,

how can i do some gallery group with listing?

thx

**Comment by jsor** [comment]
Lity doesn't support galleries, see #11.

**Comment by Studioartcz** [comment]
What? Lightbox without galleries support? 
I am sad, lity looking very good.

What about pull request from https://github.com/hyperking/lity/commit/7f58acd5a69e115d67f4b04b338cda0a7393d5f3#commitcomment-18531856 do you will accept?

**Comment by jsor** [comment]
Nope, see #11.
