### ISSUE TITLE
video autoplay on or off option

### ISSUE THREAD

**Issue by pravinweb** [jsor/lity#58]
Hi,

Thanks for this great plugin.

1) When we use youtube video link as href (<a href="//www.youtube.com/watch?v=XSGBVzeBUbk" data-lity>iFrame Youtube</a>) - it by default has autoplay on option for youtube video. could it be possible you to make it optional

2) also when I tried to to open by placing inside inline div ex: <div id="inline" style="background:#fff" class="lity-hide">
<iframe width="560" height="315" src="https://www.youtube.com/embed/XSGBVzeBUbk" frameborder="0" allowfullscreen></iframe>
</div>

video couldn't be responsive any more

Thanks,
Pravin

**Comment by jsor** [comment]
Simply append autoplay=0 to the URL.

```
https://www.youtube.com/watch?v=XSGBVzeBUbk&autoplay=0
```

**Comment by pravinweb** [comment]
Many Thanks :) its so simple

**Comment by jsor** [comment]
👍
