### ISSUE TITLE
Inline HTML is not scrollable if taller than window height?

### ISSUE THREAD

**Issue by marcusandrew** [jsor/lity#60]
Hey,

Firstly great work! Superb, lightweight plugin. Really impressed.

I'm currently using in 2 places on a site I'm building. The first one is a Vimeo popup which works great, the 2nd one I'm having issues with, which is Inline content.

My content is taller than the browser window, but I'm unable to get the inline content to scroll?

Your help would be greatly appreciated.

Cheers

**Comment by jsor** [comment]
Have you tried to set `overflow:auto` at the root element of your inline content?

**Comment by marcusandrew** [comment]
Hey,

I found a workaround and set `overflow-y:auto` on `.lity-wrap` which works ok up to a point. The only issue I have now with the Inline is that the Close icon is obscured by the scrollbar (i dont want to have the scrollbar shown on the actual Inline element as it looks terrible).

![close_icon_issue](https://cloud.githubusercontent.com/assets/15350324/18625223/0029293e-7e45-11e6-83fe-9a8dac37f5d7.jpg)

I have tried tweaking `.lity-close` and changing the right and top values but this seems to create a weird jump when the icon is clicked on...

![icon_jump](https://cloud.githubusercontent.com/assets/15350324/18625338/ed54c45c-7e45-11e6-804d-048798cc4908.gif)

Any thoughts?

Many thanks

**Comment by jsor** [comment]
You might tweak the `:active` style: https://github.com/jsor/lity/blob/master/src/lity.less#L156

**Comment by marcusandrew** [comment]
That worked great. Thanks!

Going back to my original issue. If I do attach `overflow-y: auto` to  `lity-wrap` I have just noticed that It may not always be positioned in the correct place when the overlay is fired...

![position_wrong](https://cloud.githubusercontent.com/assets/15350324/18626838/4775975a-7e4f-11e6-8365-2db253fd30f8.gif)

If I attach overflow to my root element, is it possible to hide the scrollbar on that? As it looks terrible.

![hide_scrollbar](https://cloud.githubusercontent.com/assets/15350324/18626894/ab54348e-7e4f-11e6-807a-ab0cf27d4ff6.gif)

Many thanks

**Comment by marcusandrew** [comment]
I noticed that removing `overflow-y:auto` from the `lity-wrap` element, and just applying it to my root element, still have this issue where the Inline content is shown in the wrong position, and I have to scroll up?

![inline_wrong_pos](https://cloud.githubusercontent.com/assets/15350324/18627027/89a0f1b4-7e50-11e6-95b3-ea5675cda62e.gif)

**Comment by jsor** [comment]
Could you setup a reproducible test case, eg. on jsfiddle? I can't reproduce this behaviour and i want to be sure we're talking about the exact same setup.

**Comment by marcusandrew** [comment]
Thanks buddy. Will send you a quick message, as it would take quite a bit to set this up on jsfiddle.

**Comment by jsor** [comment]
The down-scroll happened due to a bug in lity. I fixed that in [v2.1.0](https://github.com/jsor/lity/releases/tag/v2.1.0). Could you try the new version?

**Comment by marcusandrew** [comment]
Down-scroll issue fixed in the latest version. Nice work Jan.

So my two remaining issues (tweaks) here are...

Is there anyway to hide the scrollbar on my inline content?

And how can I move my inline content down so it's not butt-up to the top of the browser window?

If i do, for example `margin-top: 100px;`  on my root element the bottom of the inline content gets cut off?

Many thanks

**Comment by marcusandrew** [comment]
Down-scroll issue fixed! Thanks Jan.

Is there anyway (with Inline HTML) to have the scrollbar visible at the far right of the screen as you would normally?

 I have an example below...

![scrollbar_back](https://cloud.githubusercontent.com/assets/15350324/18630533/2d9e7bc4-7e65-11e6-8486-7b47b33fb704.gif)

Many thanks

**Comment by marcusandrew** [comment]
I have tried a few different methods but they then make the black background overlay non-clickable.

**Comment by jsor** [comment]
Lity isn't really suited for this kind of setup. But the following css tweaks might get you in that direction:

```css
.lity-active body {
    overflow: hidden;
}
.lity-inline:not(.lity-loading) .lity-content > * {
    max-height: none !important;
}
.lity-inline .lity-wrap {
    overflow: auto;
}
.lity-inline .lity-content {
    margin: 20px 0;
}
```

**Comment by marcusandrew** [comment]
Will try them out. Thanks again for the support. Much appreciated.
