### ISSUE TITLE
Linking to a specific portion of a Vimeo video?

### ISSUE THREAD

**Issue by danieledistanio** [jsor/lity#61]
Hi Jan,

great work, I'm trying to understand if I can use it.

As of now, I'm not able to open a video at a specific time. Vimeo supports:

#t=1m15s

for example to go to 1minute 15seconds, but when video opens it starts from the beginning. While clicking on the link in the inspector opens a new page at the correct time.

Do you know if a workaround exists?

Thank you, have a great day!!

**Comment by jsor** [comment]
This is fixed in [v2.1.1](https://github.com/jsor/lity/releases/tag/v2.1.1). URLs with hashes should work now.

**Comment by danieledistanio** [comment]
Oh yes it does, thank you very, very much!! ;-)
