### ISSUE TITLE
Will-change instead of transform: translateZ(0); hack?

### ISSUE THREAD

**Issue by liltinkerer** [jsor/lity#62]
Probably lity should use new [will-change](https://developer.mozilla.org/en/docs/Web/CSS/will-change) CSS property instead of old translate hack to force GPU rendering.

Here's a good starting point. I'm sure what is the best way to implement it and if it's feasible to use them together, but here's a good article [from Opera about the property](https://dev.opera.com/articles/css-will-change-property/).

**Comment by jsor** [comment]
Thanks for the suggestion. I've always been a little bit afraid of will-change since it can do more evil than good when used incorrectly. I'm not sure there will be a great benefit but i'm open for pull requests.

Btw, we're not using a translate hack in Lity. Were do you see it?

**Comment by liltinkerer** [comment]
It is a bit experimental, just wanted to bring up the discussion so maybe people who know more about it can share their knowledge.

About the hack. [It's here](https://github.com/jsor/lity/blob/master/src/lity.less#L186), or no?

**Comment by jsor** [comment]
No, IIRC, that's a hack to make `-webkit-overflow-scrolling: touch;` work correctly on old iOS versions (and could probably removed now).

I'm closing this for now. As the article you linked states, `will-change` is best implemented via JavaScript and we can't really be sure what exactly will be animated. The user might change the animation to something different as configured via the default CSS.

If anything, this could be implemented as a optional plugin which hooks into the Lity events.
