### ISSUE TITLE
Lity opens lightbox twice

### ISSUE THREAD

**Issue by michaelwilhelmsen** [jsor/lity#64]
I'm having an issue where the lity lightbox is opening links twice.
I'm only including the files once, and have no js errors. Is this a bug or a mistake in the way I've set it up? I couldn't find any information on this elsewhere, but you can see the issue [here](http://www.wilfa.no/dev/).

`<a class="video-lightbox" href="https://youtu.be/64aA-Qj5ZcE" data-lity><img src="..." /></a>`

```
(function($) {
  $(document).on('click', '[data-lity]', lity);
})(jQuery);
```

**Comment by jsor** [comment]
You don't need the second code block as thats the default behaviour of lity.

**Comment by michaelwilhelmsen** [comment]
Thank you 👍 That fixed it

**Comment by kumaunix** [comment]
What are the possibilities of a link to be opened twice by lity, please advice

**Comment by khkesav** [comment]
> What are the possibilities of a link to be opened twice by lity, please advice

Check if you have added Lity js twice.
