### ISSUE TITLE
Zepto support broken?

### ISSUE THREAD

**Issue by Every0ne** [jsor/lity#65]
Zepto support seems to be broken in [2.1.1](https://github.com/jsor/lity/tree/v2.1.1). Neither Zepto 1.1.6 nor 1.2.0 work fully. Tried with downloaded build + modules and with build generated by [builder](http://github.e-sites.nl/zeptobuilder/). In all cases the lightbox opens, but cannot be closed (throws an error of different content, depending on what build was used).

**Comment by jsor** [comment]
Hi,

thanks for the report. Yes, Zepto support was broken. I fixed a small compatibility issue (58a5c78a5cff89b85093df20b166f2312a2019ad) and noted the requirement of the [data module](https://github.com/madrobby/zepto/blob/master/src/data.js) (225d01f9bbee39076d99c73135697bb68b8a1311).

Could you give [v2.2.0](https://github.com/jsor/lity/releases/tag/v2.2.0) a try and report if something is still broken?

**Comment by Every0ne** [comment]
[2.2.0](https://github.com/jsor/lity/releases/tag/v2.2.0) fixes this issue, thank you.
