### ISSUE TITLE
Changing alt tags with Lity instance

### ISSUE THREAD

**Issue by jrmedd** [jsor/lity#66]
What's the correct way for changing an image's alt tag with a Lity instance? I tried:

`instance.options('lity-desc', 'A picture of something');`

But that didn't work. Any ideas?

Thanks.

**Comment by jsor** [comment]
Add a `data-lity-desc` attribute to the opener element.

```html
<a href="image.jpg" data-lity data-lity-desc="A picture of something">
  Open image
</a>

**Comment by jrmedd** [comment]
Thank you. Is there any way to this programmatically?

**Comment by jsor** [comment]
Unfortunately not. A dirty workaround would be to fake the opener element.

```js
lity('image.jpg', {}, '<span data-lity-desc="Test"/>');
```

**Comment by jrmedd** [comment]
Good enough for me 👍 

Thanks again.
