### ISSUE TITLE
External URl's not loading?

### ISSUE THREAD

**Issue by jbrabants** [jsor/lity#67]
Everything working fine: vimeo, images, youtube, but when I try to load a webpage the only thing I get is a black lightbox without any content. 
![screen shot 2016-10-14 at 09 39 21](https://cloud.githubusercontent.com/assets/5476404/19379413/2191194a-91f2-11e6-8e53-cadc31145a5d.png)

**Comment by jsor** [comment]
Check the console. Google sends a `X-Frame-Options`header which prevents from being displayed inside a (i)Frame.
