### ISSUE TITLE
Turn off youtube related videos and titles

### ISSUE THREAD

**Issue by Mutpowr** [jsor/lity#69]
Adding ?rel=0&amp;showinfo=0 will hide the title but show related videos (should be hidden).

Adding ?showinfo=0;rel=0 will show the title (should be hidden) but hide related videos.

Adding ?rel=0&amp;controls=0&amp;showinfo=0 will hide the title hide related videos but show the controls (should be hidden).

Seems to be a small bug on how it processes the "?" sign I believe.

**Comment by jsor** [comment]
Could you post a complete code snippet?

The following code works correctly for me:

```html
<a href="http://www.youtube.com/watch?v=XSGBVzeBUbk&amp;rel=0&amp;controls=0&amp;showinfo=0" data-lity></a>
```

**Comment by onmarketing** [comment]
This is not works for me, please fix the issues.

Thanks,

Shaun.
