### ISSUE TITLE
Allow YouTube API Parameters

### ISSUE THREAD

**Issue by nathanchase** [jsor/lity#7]
I'd like to be able to use the YouTube API parameters (available at https://developers.google.com/youtube/player_parameters?hl=en#Parameters) when using Lity. It seems like if I have a URL like https://www.youtube.com/watch?v=ngElkyQ6Rhs&autoplay=1&showinfo=0&rel=0&iv_load_policy=3 everything gets stripped except for the autoplay=1. I poked around in the source and saw where the regex takes place and figure there is probably a way to edit the code a bit to allow for more parameters. Thoughts?

**Comment by jsor** [comment]
Good idea! I've implemented this in d808314c035b03d30b3ad57af3b2bb472d0635c0. Could you try the files from master if it works as expected?

**Comment by nathanchase** [comment]
Works perfectly! I get this rendered into the DOM:

<div class="lity-iframe-container" style="max-height: 955px;"><iframe frameborder="0" allowfullscreen="" src="//www.youtube.com/embed/ngElkyQ6Rhs?autoplay=1&amp;showinfo=0&amp;rel=0&amp;iv_load_policy=3"></iframe></div>

Thanks! If you add this as a new release I can just update by bower.json to reference this new version. Much appreciated!

**Comment by nathanchase** [comment]
As an aside, that "max-height" parameter could probably be something not hardcoded into the lity-iframe-container div. Perhaps moved to the css instead?

**Comment by jsor** [comment]
[v1.4.2](https://github.com/jsor/lity/releases/tag/v1.4.2) tagged.

Regarding `max-height`: yes, i want to maintain support for IE8 at the moment.
