### ISSUE TITLE
Instagram Padding and Being Responsive

### ISSUE THREAD

**Issue by mraypold** [jsor/lity#70]
The Instagram plugin had a padding-top css value of 113.07189542% and I am curious how this was arrived at, as I am trying to work through how to make Instagram embeds more responsive.

The code in question (though, this may not be the root of the problem):
`
.lity-instagram .lity-iframe-container {
  padding-top: 113.07189542%;
}
`

My issue seems to be contained to Instagram embeds that contain videos shot in landscape mode (eg: [here](https://www.instagram.com/p/BA3y_khGM5Y/)).  Videos in portrait mode work perfectly.

**Comment by jsor** [comment]
This is generated from the less source file: https://github.com/jsor/lity/blob/master/src/plugins/instagram/instagram.less

**Comment by mraypold** [comment]
Thank you for pointing me in the right direction. I was able to get the correct aspect ratios using the `lity:ready` event and overriding `.lity-instagram .lity-iframe-container`.

**Comment by jsor** [comment]
Did you managed to detect whether you're linking to a video from the URL? Anything which could be added to Lity?

**Comment by mraypold** [comment]
Here are two test cases which I was working with. Instagram pictures work perfectly. Videos have a couple issues with aspect ratios if they don't conform to the traditional Instagram square standard. In my use case, I was embedding Instagram videos.

1. [An Instagram video post which is shot in landscape mode instead of the traditional Instagram squares](https://www.instagram.com/p/BA3y_khGM5Y/). Lity treats this as an iframe using the Instagram plugin.

2. [An Instagram video post which is shot in portrait mode](https://www.instagram.com/p/BI-RAqdDAdM/). Lity also treats this as an iframe using the Instagram plugin.

My solution was to use the lity:ready event to update the css properties, because I know the video width and height ahead of time using the Instagram API.

```
const newPadding = (parseInt(vidHeight) + 80) / (parseInt(vidWidth)) * 100;

$(document).on('lity:ready', function() {
  $('.lity-instagram .lity-iframe-container').css({ 'padding-top': newPadding + '%' });
});
```

I don't think this is an ideal fix and you may be able to come up with a CSS only solution to adjust the iframe to non standard Instagram ratios.

One other idea for a solution, for those who don't know the video width and height ahead of time might be to extract it from the metadata returned in the Instagram embed. I didn't investigate this fully, but Instagram does return some extra information in the returned html.

I added the above links to `test/functiona/plugins/instagram.html` and took these screenshots to better show the problem. The Instagram profile is not my own, but I found it convenient to test with.

<img width="822" alt="screen shot 2016-10-20 at 1 09 51 pm" src="https://cloud.githubusercontent.com/assets/6334968/19576141/bb6850f0-96c6-11e6-8bbc-a1f30a77e2a9.png">

<img width="724" alt="screen shot 2016-10-20 at 1 12 58 pm" src="https://cloud.githubusercontent.com/assets/6334968/19576212/f65350ac-96c6-11e6-9224-2ecd351ad12c.png">

**Comment by jsor** [comment]
Thanks a lot for the detailed response. Probably using the embed API instead of the iFrame directly will help here because it looks like it is setting a height for the iFrame. Will play with it...
