### ISSUE TITLE
How to force the size of the Lightbox window by pixel size or percentage

### ISSUE THREAD

**Issue by inglesuniversal** [jsor/lity#71]
My code requests a Lightbox which in turn will load a SHARE window written in php

CODE USED:

```
                title: 'Share',
                image: '/64/share-icon.png',
                click: function(){
                // Open a URL in a lightbox
                var lightbox = lity('https://domain.com/share.php?f=<?php echo $file_id; ?>');
                // Bind as an event handler
                $(document).on('click', '[data-lightbox]', lity);
                }
```

My Question is simple... How can I control the size of the Lightbox Window when clicking the triggering image?  Can the size of the Lightbox window be part of the LINK or settings JUST for this particular case within my code, by specifying the width and height in pixels or percentage?

Best regards and thanks for the previous HELP provided.

**Comment by jsor** [comment]
There is no way to force the size of the lightbox. The easiest solution would be to register a custome handler.

```js
lity.handlers('share', function(target, instance) {
    if (0 !== target.indexOf('https://domain.com/share.php')) {
        return false;
    }

    return lity.iframe(target, instance);
});
```
Then, the lightbox element contains a class `lity-share` and you can use this class to style lightboxes which where opened for URLs starting with `https://domain.com/share.php`.
```html
<div class="lity lity-iframe lity-opened lity-share">
...
</div>
```
