### ISSUE TITLE
Maintaining UPLOAD instance when Lity (Lightbox) is closed accidentally

### ISSUE THREAD

**Issue by inglesuniversal** [jsor/lity#72]
I am ENJOYING the quality of your code so much!  Way to go!!!

In the event that I click on an image (icon) and a php page from my site (uploader script) is loaded into the Lity (Lightbox) using your sample code:

`<a href="https://mydomain.com/uploader/" data-lity><img src="/upload_icon_large.png" border="0" width="225"></a>`

HOW can I keep the upload INSTANCE active, by that I mean NOT to lose the data or files I am uploading from my local computer, IF by mistake I close the Lity (Lightbox) ?

Your HELP is appreciated.

**Comment by inglesuniversal** [comment]
Hi again... I tried to make use of the CODE you kindly provided and it works fine, but then again, if I close the UPLOAD window and re-open it even after a few seconds, my UPLOAD instance is GONE... 

Could you kindly REVIEW this code to see where I messed up? Thanks Jsor!!!

`<div style="position:absolute;top:55px;left:-1px;">
  <a href="#uploader" data-lity><img src="icons/upload_icon_large.png" border="0" width="225"></a>

<div id="uploader" style="overflow:auto;background:#0073ff;color:#ffffff;font-size:18px;text-shadow: 4px 4px 8px #000000;padding:20px;width:600px;max-width:100%;border-radius:6px">
UPLOADER...
    <p>
    <button class="green_button button2" onclick="UploadLOCAL()"  data-lity-close>Upload Local Files</button>
    <button class="green_button button2" onclick="UploadREMOTE()" data-lity-close>Upload Remote Files</button>
    <button class="red_button button2"   data-lity-close>Cancel</button>
    </p>
</div>


<script>
function UploadLOCAL(){
// Open a URL in a lightbox
var lightbox = lity('https://mydomain.com/upload/');

// Bind as an event handler
$(document).on('click', '[data-lightbox]', lity);

    if (0 !== target.indexOf(lightbox)) {
        return false;
    }

    lity.element()
        .addClass('lity-iframe')
        .on('lity:open', function() {
            lity.element()
                // Unbind Lity's close events
                .off('click', '[data-lity-close]')

                // Bind own close event
                .on('click', '[data-lity-close]', function(e) {
                    if (e.lightbox === this) {
                        if (!confirm('Are sure?')) {
                            return;
                        }

                        lity.close();
                    }
                })
            ;
        })
    ;

    return '<div class="lity-iframe-container"><iframe frameborder="0" allowfullscreen src="' + lightbox + '"/></div>';
}
</script>

`

**Comment by jsor** [comment]
As is said, state can't be preserved between lightbox instances. What the custom handler does is simply adding a confirm dialog when closing the lightbox. It just prevents accidently closing the lightbox.

There are a few errors in your code.

1. The `data-lity-close` attribute should be only added to  elements which should close the lightbox.
2. The custom handler i post must be global code (eg. after you load lity via `<script>`), not inside a event handler.
