### ISSUE TITLE
How to fit the video ratio size?

### ISSUE THREAD

**Issue by jatiyanon** [jsor/lity#73]
[Link to Pic](http://www.uppic.org/image-61A5_5810A4DC.jpg)

**Comment by jsor** [comment]
I can't open that image. Could you describe the problem a little bit and probably provide a reproducible test case, eg. on jsfiddle?

**Comment by jatiyanon** [comment]
Sorry,

[pic](http://kiekiedelarue.com/others/pic.jpg)

[jsfiddle](http://jsfiddle.net/Lbenwsax/3/)

**Comment by jsor** [comment]
The iframes have a default ration of 16:9 (see https://github.com/jsor/lity/blob/master/src/lity.less#L5). This ration is used here: https://github.com/jsor/lity/blob/master/src/lity.less#L183

If you want to change the ratio, eg. to 2:1 (the ration of the video you linked), you overwrite this with:

```css
.lity-iframe-container {
  padding-top: calc(1/2 * 100%);
}
```

I've updated the jsfiddle: http://jsfiddle.net/Lbenwsax/4/
