### ISSUE TITLE
YouTube Video Start at Time 

### ISSUE THREAD

**Issue by brianandgarcia** [jsor/lity#75]
`<a href="//youtu.be/WJ88GhJJI3Q?t=1h13m14s" data-lity>`

I've tried a few different variations, but I can't get it to play the video at that specific time, always starts from the beginning. 

Any ideas? Great plugin, by the way 👍

**Comment by jsor** [comment]
Looks like for embeds, only `?start=<seconds>` works, eg. 

```html
<a href="//youtu.be/WJ88GhJJI3Q?start=4394" data-lity>Link</a>
```
