### ISSUE TITLE
Lightbox doesn't pop-up

### ISSUE THREAD

**Issue by jkoopman93** [jsor/lity#78]
Hello!

I've been building my own portfolio website with a friend of mine. For some school projects I made some movies and animations, so I want these to pop up in a lightbox inside my work section. I think Lity is a very easy and cool looking tool for this. I added the 'dist' and 'vendor' files to my own files in Coda (program I'm using for all my files and coding) and I added the code to my index.html (which I use for my project pages). When I hove my mouse over the image I see in the bottom corner the link to my Vimeo movie, but when I click nothing happens. This is my test website: http://jochemkoopman.nl/wip/work/thecloud/

I hope you can help me out! I'm pretty new at all this coding...

**Comment by jsor** [comment]
Looks like you're not linking to the lity files correctly:
![screenshot](https://cloud.githubusercontent.com/assets/55574/20344446/15c78c32-abf3-11e6-8d81-b83697db184a.png)

Additionally, you do not need to include `vendor/jquery.js` since jQuery is already included (`http://code.jquery.com/jquery-1.11.2.min.js`).

**Comment by jkoopman93** [comment]
Thanks! It's finally working on that page. But I have a new problem now.... I copied the exact same code from http://jochemkoopman.nl/work/thecloud/ to http://jochemkoopman.nl/work/uprooted/
The pop-up opens on the first one (/thecloud/) but not in the second one (/uprooted/). It's the exact same code, only another vimeo link and headers/text.... Can you maybe see what's going wrong here?

**Comment by jsor** [comment]
Glad you solved it. 👍
