### ISSUE TITLE
Loading hint

### ISSUE THREAD

**Issue by alejo-moreno** [jsor/lity#79]
Sometimes the youtube or vimeo player takes some time in appear ( 4 to 7 secs depending the network, this is mostly in mobile) and the iframe background is covering the loading label so the user just see a black square. I tried append a custom loader but iframe removes the content. Is there a way the loading label can work properly and stays until the embed video is loaded?

**Comment by jsor** [comment]
The iframe must be hidden until it is loaded to make the loader visible and i've not found a reliable way to detect when an iframe is loaded. So, no, sorry.
