### ISSUE TITLE
[BUG] Inconsistent focus management

### ISSUE THREAD

**Issue by mrwweb** [jsor/lity#80]
I am loving lity so far in the first few days of using it. The focus on accessibility is what led me to you! I believe this is a bug and not expected behavior. Happy to be wrong :)

## To Reproduce
1. Open any lightbox instance
1. Hit `ESC`

\- OR -

1. Open any lightbox instance
1. Click in black "background" area to close lightbox

## Current Behavior
Focus is returned to document root.
Example: After closing lightbox, hitting `TAB` once goes to the first-in-source "Skip to Content" link.

## Expected Behavior
Focus is returned to last-focused element (usually the lightbox-triggering link element).

Using the "X" close button via keyboard and mouse exhibits this behavior already, leading me to expect the same result from all methods of closing the lightbox.

I'm not familiar enough with the library yet to be able to suggest a fix.

**Comment by jsor** [comment]
Hi,

thanks for the report. I've released a fix in [v2.1.1](https://github.com/jsor/lity/releases/tag/v2.2.1).

**Comment by mrwweb** [comment]
Awesome. I should be able to update and test fixes today or tomorrow. Will report back if anything is still of. Thanks for such a quick response!

**Comment by mrwweb** [comment]
Quick tests look good!
