### ISSUE TITLE
Manipulating the browser history

### ISSUE THREAD

**Issue by liltinkerer** [jsor/lity#81]
I know you want to keep lity as lightweight as possible, but would you be interested in implementing or taking a pull request on manipulating browser history?

I've done some user testing and on mobile people keep hitting the back button when they want to close the lightbox and of course it doesn't behave they way it should.

Thoughts?

**Comment by jsor** [comment]
A simple custom solution would be:

```js
$(document).on('lity:open', function () {
    if (location.hash === '#lity') {
        return;
    }
    history.pushState({}, '', '#lity');
});

$(document).on('lity:close', function () {
    if (lity.current()) {
        return;
    }
    history.replaceState({}, '', location.href.split('#')[0]);
});

$(window).on('hashchange', function () {
    if (!location.hash && lity.current()) {
        lity.current().close();
    }
});
```
Does that help?

**Comment by liltinkerer** [comment]
Thank you. The custom solution was not necessary since I already have something similar implemented. I was just wondering if this is something you think should be implemented to lity itself or if you need any help with it.

**Comment by jsor** [comment]
I thought about adding this, but it could become quite complex because of stacked/nested lightboxes. I'm interested in your solution though :)

**Comment by JordanSayner** [comment]
I was wondering if we can link a modal to a specific modal, with your method above, you if you refresh, the modal doesnt open. I understand this method was to make the back button work, but it would be helpful if a user goes to that url (with a hash) a the right modal opens.

**Comment by JordanSayner** [comment]
Using this code i got it working for inline modals in case anyone is interested

```
        $(document).on('lity:open', function () {
            if (window.location.hash) {
                return;
            }
            setTimeout(function () {
                var getHash = $('.lity').find('.modal').attr('id');
                history.pushState({}, '', '#' + getHash);
            }, 100)
        });

        $(document).on('lity:close', function () {
            if (lity.current()) {
                return;
            }
            history.replaceState({}, '', location.href.split('#')[0]);
        });

        $(window).on('hashchange', function () {
            if (!location.hash && lity.current()) {
                lity.current().close();
            }
        });

        $('a[href="' + location.hash + '"]').click();
```

**Comment by jsor** [comment]
Thanks, closing for now. Feel free to reopen if needed.
