### ISSUE TITLE
issue with clicking on link but opens 2 lightboxes

### ISSUE THREAD

**Issue by fineartist99** [jsor/lity#83]
I don't know if you could take a look at this or not but if you go to this site and in the top part there are 3 slides in the slideshow, the 3rd slide uses this lity code to open the youtube video in a lightbox 
http://yourefolio.com/newh/

if you click on that 3rd slide and open the video it plays with no issue but go ahead and close it, you see you have to close it twice.  Then what I did was clicked on the 3rd slide again and paused the video and you'll see you still hear the sound - that's because there is 2 lightboxes that open up, one on top of the other.

If you could take a look at this and let me know how to resolve this issue that would be great.  Thank you.

**Comment by jsor** [comment]
Could create a minimal reproducible test case? You site uses a *lot* of scripts :)

**Comment by fineartist99** [comment]
Yeah I know, that's the issue I bet and to comb through everything would take forever.  Thanks though, I'll just use it inline : )
