### ISSUE TITLE
Additional source support? Soundcloud, Bandcamp, Reverbnation, etc?

### ISSUE THREAD

**Issue by ghodsfry** [jsor/lity#84]
Feature request:  Soundcloud, Bandcamp and/or Reverbnation streaming support. Each site offers iframe code for embedding their content similar to Youtube/Vimeo.

Alternate question:  If it is too difficult to convert one of their URLs via regex into a viable container is it possible to pass the <iframe></iframe> code directly into LITY instead?

**Comment by jsor** [comment]
It is quite easy to add additional handlers, see the instagram plugin for example:
https://github.com/jsor/lity/blob/master/src/plugins/instagram/instagram.js#L14-L29

**Comment by ghodsfry** [comment]
Cheers - I had noticed the instagram handler. I thought it was worth asking if additional handlers could be added to the core just in case you were already considering additional service providers. Happy for you to close this request and I'll investigate adding my own handlers for my needs.

**Comment by jsor** [comment]
Feel free to open a PR. Or you could provide it in your own package as third-party plugins and i'm happy to link it in the README.
