### ISSUE TITLE
How to define the size of a Lity window

### ISSUE THREAD

**Issue by inglesuniversal** [jsor/lity#85]
How can I define (before opening a Lity window) its size and z-index of the resulting Lightbox.

Can it be global or set for each different call?

Thanks!

Current code:

`
            var lightbox = lity('/mydomain_dir/code.php');
                    // Bind as an event handler
            $(document).on('click', '[data-lightbox]', lity);
`

**Comment by jsor** [comment]
You could use a customer handler (see #71 for an example) or bind to [`lity:open`](https://github.com/jsor/lity/tree/2.x#lityopen) and add your custom logic.

**Comment by CptChaos** [comment]
Would be nice if Lity would get options which support height and width.

**Comment by jsor** [comment]
Feel free to open a PR for this feature. Closing for now.
