### ISSUE TITLE
IE 11 - Can't Close Lity with Video

### ISSUE THREAD

**Issue by atelierandy** [jsor/lity#86]
Hi 

I can't seem to close the lity window with a video (example code below) in IE11.

This only seems to be an issue in IE11 and only seems to to happen when a video is in the window, I don't have this issue with other iframe content or inline windows.

<a href="https://www.youtube.com/watch?v=x8u0n4dT-WI" data-lity>

**Comment by jsor** [comment]
Could you setup a minimal reproducible test case, eg. on jsfiddle?

**Comment by atelierandy** [comment]
Sure here - https://jsfiddle.net/91czzx07/3/

Am testing on Windows 8.1 IE 11 Latest

Issues seems to be something to do with the inline SVG inside the a tag. If you remove the SVG it works?

I can see the following error in IE11 but it doesn't mean anything to me. Sorry my js knowledge is limited.

line 515: activeElement.focus();
Object doesn't support property or method 'focus'

**Comment by tjdunklee** [comment]
I had this same exact problem and the CSS property "pointer-events:none" on the SVG element solved it for me. This article was a lifesaver:

https://css-tricks.com/links-inline-svg-staying-target-events/

There may be a way to check for this situation in the code as mentioned in the article above. Any thoughts @jsor? Thank you for all your work on this.

**Comment by jsor** [comment]
Thanks for the infos @atelierandy and @tjdunklee! It is indeed an issue with IE11 where you can't focus SVG elements.

Workarounds are `svg{pointer-events:none;}`as mentioned by @tjdunklee or `<svg focusable="false"></svg>`([Source](http://stackoverflow.com/a/18646112/422773)).

I've added a patch which catches and ignores exceptions when trying to focus the active element in 230320511d1047a4d6425b26cda527f3e42e6a20.

Could you try https://raw.githubusercontent.com/jsor/lity/2.x/dist/lity.js and report back if it fixes the issue for you? Thanks!

**Comment by atelierandy** [comment]
Thanks guys

@jsor the patch works for me, thanks.

By the way forgot to mention the plugin is great and really light weight.

**Comment by jsor** [comment]
Thanks for reporting back. Fix released in [v2.2.2](https://github.com/jsor/lity/releases/tag/v2.2.2).

**Comment by tjdunklee** [comment]
Thanks for the quick fix @jsor! I had a chance to test today and the fix works perfectly. Cheers.

**Comment by jsor** [comment]
Great! Closing now, feel free to reopen if needed.
