### ISSUE TITLE
Description / Titles

### ISSUE THREAD

**Issue by SimonKese** [jsor/lity#87]
Hi, 

thanks for this great lightbox.
Is there a way to add a description / title below a video or image in the lightbox? 
Thanks!

**Comment by jsor** [comment]
This is not possible out of the box. See eg. #37 for a possible solution.

**Comment by studio404pl** [comment]
#37  is not up to date according to latest release. Here is the code that handles titles properly.

```
jQuery(document).on('lity:ready', function(event, lightbox, triggeringElement) {
	 jQuery(event.currentTarget.activeElement).find('.lity-content').prepend('<h2>' + lightbox.opener().data('title') + '</h2>');
 });
```

**Comment by jsor** [comment]
Thanks.
