### ISSUE TITLE
Appending a caption is not visible on shorter browser windows

### ISSUE THREAD

**Issue by aaronbushnell** [jsor/lity#88]
I'm using #17 to add a custom caption to a Lity instance. However, the dynamic `max-height` on the `img` element is not accounting for appended content. This causes issues where shorter browser windows (like a mobile device in landscape) cuts the caption off. Attached a gif for an example.

Any thoughts on how to correct this?

![Cut off caption](https://cl.ly/3C470i2k3g3H/landscape.gif)

**Comment by liltinkerer** [comment]
Do `max-height: calc(100% - 20px);` -- 20 px is an example for the caption height.
By the way, this question is probably more suitable to [StackOverflow](http://stackoverflow.com/) than here :wink:

**Comment by aaronbushnell** [comment]
@liltinkerer Thanks for the reply! I thought about using `calc()`, but the caption could be any length. Especially as the browser shrinks in width the caption will wrap any number of lines. So I think that's too unpredictable for the use-case.

I also thought the question was more relevant here in case it led to a change in the codebase and someone wanted to note this issue in a PR or something.

**Comment by liltinkerer** [comment]
If I understand correctly, it didn't lead a change in the codebase in a sense the caption is possible to add thanks to callbacks.

But anyway, you can get the height of the caption and subtract it from another element.

var caption_height = $lightbox.find('p.caption'').height();

Then find the element you want to change and subtract caption_height :+1:

**Comment by aaronbushnell** [comment]
> the caption is possible to add thanks to callbacks.

Fair point! I remember the author saying caption support would not be a native feature. I'll see if there's a way to calculate this dynamically!
