### ISSUE TITLE
Does not handle .svg files correctly

### ISSUE THREAD

**Issue by creynders** [jsor/lity#9]
The .svg file _is_ shown, but within a viewport with scroll bars.

![screen shot 2015-09-22 at 12 34 42](https://cloud.githubusercontent.com/assets/436347/10016334/7932fcde-6126-11e5-9ca1-646203a90ab4.png)

**Comment by jsor** [comment]
Could you attach the svg file?

**Comment by creynders** [comment]
I assume all it takes is adding "svg" to [the regex](https://github.com/jsor/lity/blob/master/src/lity.js#L20)? 

I can't attach svg files here. Sec, I'll post it somewhere.

**Comment by creynders** [comment]
https://github.com/d-pac/d-pac.docs/blob/master/src/developer/assets/Selection%20flow.svg
