### ISSUE TITLE
Why is there a 2px padding/space on the right side of the lightbox?

### ISSUE THREAD

**Issue by aslamdoctor** [jsor/lity#90]
To confirm this issue, I just tested this from http://sorgalla.com/lity/ by using Image demo.  Check the image below.
![screenshot](https://cloud.githubusercontent.com/assets/171670/21892284/0e05a2f0-d8fc-11e6-8d12-916e77322b14.jpg)

For small boxes this is not noticeable but for the lightbox with 100% width, the white line on the right can be seen clearly.

**Comment by jsor** [comment]
This cause by https://github.com/jsor/lity/blob/2.x/src/lity.less#L51
TBH, i'm not sure anymore why this is there, you can probably just remove it.

**Comment by aslamdoctor** [comment]
No probs, I added below code to my stylesheet, and it fixed the issue.

```
.lity-container{
    margin-left:3px;
}
```

as the modal box was going out of screen on left side. I thought may be some error in my stylesheet but it is on the demo too. It's just because of dark background, it's not noticeable.  But for the full width modals with like 10-15px spacing on left-right side( client request :P ), it is noticeable.

**Comment by styromaniac** [comment]
This should be in Lity. I made a bug report about this, thinking that .lity-wrap:before didn't need a margin-right of -.25em.
