### ISSUE TITLE
Display inline content from another URI

### ISSUE THREAD

**Issue by drupov** [jsor/lity#91]
Is it possible to display inline content from another URI in lity? Same as now with inline, only the defined content lies on another page (of course by displaying only the content that is targeted), opening external URL already works.

**Comment by jsor** [comment]
No sorry, this is ot possible out-of-box.

**Comment by SparrowSquire** [comment]
This is exactly what im trying to do! 
<a href="#targetName" data-lity data-lity-target="/some_url_containing_php_vars">Click</a> 
This opens the new page, but adds an iframe to it!! need to do it without an iframe... ;'(

**Comment by jsor** [comment]
As i said, that is not possible with lity, sorry.

**Comment by SparrowSquire** [comment]
In case anyones interested you can work around it by running a `new XMLHttpRequest();` and then using `.onload` to inject the URL into a container.

**Comment by jsor** [comment]
Glad you solved it yourself 👍

**Comment by drupov** [comment]
@SparrowSquire can you give an more detailed example on how you do it with `new XMLHttpRequest();`?

Where do you have that code?

Thanks!

**Comment by SparrowSquire** [comment]
HTML p1
`<a href="#lityContent" data-lity id="anchor">CLICK ME</a>
<div id=""></div>'
`
 <script>
   var url = "/some-example/VAR/VAR/ATVAR';
   var request = new XMLHttpRequest();
   
   request.open('GET', url, true);
   request.onload = function() {
       if (request.status >= 200 && request.status < 400) {
           var resp = request.responseText;
           document.getElementById('overlayContainer').innerHTML = resp;
       }
  };
  request.send();`
</script>
`

HTML p2 with php vars passed in url
`<div id="lityContent" class="lity-hide>this contains dynamic lightbox content but not displayed in a pesky horrible iframe!!</div>`
