### ISSUE TITLE
How to Update calling / parent page?

### ISSUE THREAD

**Issue by jwheat** [jsor/lity#94]
This has been very helpful and its really easy to implement, thank you.

My question - Is it possible for Lity to open a page, have the user select various preferences for my webapp, and when clicking save, have Lity close and update divs on the calling (parent) page?

I guess another way to phrase it, is there a way for a Lity page to change the page that opened it?  Or send back data to the calling page?

Does that make sense?
-Jon

**Comment by jwheat** [comment]
I figured out I can set parent html with something like this.  

To set the Serial Number from a lity screen -
$('#serial_number', window.parent.document).html('5405945-3434920-12');

when I click save, I save the preferences to the database, update the parent page with the new values and close lity.

**Comment by jsor** [comment]
Gald you solved it by yourself 👍
