### ISSUE TITLE
programmatically close Lity

### ISSUE THREAD

**Issue by jwheat** [jsor/lity#95]
I'm sorry for being dense and keep asking questions here - maybe like last time I'll figure it out after I post this.

I'm trying to programmatically close Lity after I've submitted the form it was displaying.

I open the form in Lity, click Submit, it properly submits and saves data.  Then I need to close it.

After the form submits I have this -
``` 
<script>
    	$(document).ready(function() {
    		// add a check mark to the list that this is completed
    		$('#configure_datetime_icon', window.parent.document).addClass('fa-check text-success');
    		// close Lity
    		$('[data-lity-close]').trigger('click');
    	});
</script>
```

My check mark displays on the parent screen as expected, but Lity doesn't close.  
What is the proper way to do that? I'm definitely doing something wrong.

 -Jon

**Comment by jsor** [comment]
You're passing `window.parent.document` as context as the second argument `$()` int the first call. You must do that too in the second:

```js
$('[data-lity-close]', window.parent.document).trigger('click');
```

**Comment by jwheat** [comment]
Amazing, thank you, that works perfectly.  Reading that makes complete sense now, I appreciated your help.
