### ISSUE TITLE
IE9 Youtube Video

### ISSUE THREAD

**Issue by atelierandy** [jsor/lity#96]
Hi

Just noticed Youtube iFrame windows don't work in Internet Explorer 9, I couldn't see any support notes anywhere so this may not be supported but thought I would mention.

Thanks

Andy

**Comment by jsor** [comment]
Lity should work with IE9. Closing for now, feel free to reopen with more information and a reproducible test case.

**Comment by bwobst** [comment]
I'm getting the same in IE 10 and 11 - the browser just prompts to either open or download the video file.

Note that I'm hosting the file myself (not on YouTube or Vimeo).

```
var lightbox = lity(mp4Url);
$(document).on('click', '[data-lightbox]', lity);
```

**Comment by jsor** [comment]
Lity doesn't work with video urls because it opens these urls in regular iframes and leaves it up to the browser to handle these.
