### ISSUE TITLE
instance.opener() never works.

### ISSUE THREAD

**Issue by nkals722** [jsor/lity#99]
It seems like the opener API doesn't work. Whether lity is opened with the data-lity attribute or programmatically - trying to get the element that initiated the event always errors out:

`$(document).on('lity:open', function(event, instance) {
   console.log('Lightbox opened');
   var opener = instance.opener();
});`

This always throws a "TypeError: instance.opener is not a function".

**Comment by jsor** [comment]
Are you sure you're not using a 1.x version? the `opener()` function has been added in 2.0.

**Comment by nkals722** [comment]
You're a smart man jsor. That is exactly what is was. Thank you!
